### ISSUE TITLE
ng-grid rowspan

### ISSUE THREAD

**Issue by minliu4** [angular-ui/ng-grid#1464]
ng-grid how to merge rows?

**Comment by juniorplenty** [comment]
@PaulL1 I believe the OP was literally asking for the html table "rowspan" behavior, where a cell can span two rows (similar to colspan). Here's an example if you're not familar:

![image](https://cloud.githubusercontent.com/assets/941119/5600489/ba54988c-928f-11e4-977f-2ff0390e715e.png)

Anyway - was about to log this same issue, can this be re-opened now that you have explicit details?

**Comment by juniorplenty** [comment]
same example, annotated:

![image](https://cloud.githubusercontent.com/assets/941119/5600542/cc055372-9290-11e4-9cb4-6d2fbb364458.png)

**Comment by juniorplenty** [comment]
Variations of this have been requested a couple other times:

- https://github.com/angular-ui/ng-grid/issues/845
- https://github.com/angular-ui/ng-grid/issues/259

**Comment by PaulL1** [comment]
OK, understand.  I'm not sure this is coming any time soon though unless someone submits a pull request including it.

**Comment by PaulL1** [comment]
This is now included in the templates tutorial: http://ui-grid.info/docs/#/tutorial/317_custom_templates.

Merging all cells in a row is reasonably straightforward, merging just some cells would be somewhat more complex, but still possible through that same mechanism.

**Comment by spencer48** [comment]
Thanks @PaulL1! This is helpful, but I think this is applicable to the use case of colspan instead of rowspan. Any ideas on a way to achieve the same merging effect vertically?

**Comment by JLLeitschuh** [comment]
If you are looking to do this you could probably do it visually using a custom cell template. I know that it's less than ideal but it will fix your problem.

**Comment by spencer48** [comment]
Awesome, it seems to be working thanks!

**Comment by infyravi** [comment]
Hi,
 I am also stuck up with the same rowspan issue and not able to find any sample example for it.
 Going through the discussion chain found that it can be done, can anyone share the sample example

**Comment by trupti18** [comment]
Hi, Has the ROWSPAN feature added to ui-grid or not? I am not able to find any inforamtion about it.

**Comment by infyravi** [comment]
found a workaround for doing it

**Comment by trupti18** [comment]
Can you share the workaround.

**Comment by NewJavaPythonDeveloper** [comment]
@trupti18 do you have a workaround for the ROWSPAN feature?

**Comment by damianbazarko** [comment]
Do you have any informations about ROWSPAN, anyone know an example of ROWSPAN ???

**Comment by danilofaria** [comment]
hello @infyravi, could you please share your solution? thanks

**Comment by bvoisin** [comment]
I arranged a RowSpan hack, suitable for my need, not necessarily for everyone:  I use _position:absolute_ on the top row's cell and _display:none_ on the spanned rows' cells. See http://plnkr.co/edit/TiQFJnyOvVECOH2RL4ha?p=preview

Everything is in the ng-style in the cell template, which uses a 'spanCompany' attribute to know the number of rows to override. We have to calculate the height and width since we are position:absolute. This also means the width has to be expressed in pixels, not %.

`ng-style="{ height:21*row.entity.spanCompany + \'px\', width:col.width+\'px\', position:\'absolute\', display:row.entity.spanCompany==0?\'none\':\'block\', borderStyle:\'dotted\', borderWidth:\'1px\'}"`

**Comment by qmy777** [comment]
@bvoisin

**Comment by qmy777** [comment]
@bvoisin 
Thanks for your solution!
But there have a big problem: when I am scrolling, the row, div.ui-grid-row is changing its style to be {transform: translateY( xxx px);} dynamically, then the display of invisible cell displays.
So, do you know have any idea to solve this problem? Thanks :）

**Comment by qmy777** [comment]
@bvoisin 
thanks for your solution; but the div.ui-grid-row has a dynamic style, "transform: translateY(); ", which is a big problem when scrolling
So, do you have any idea to solve transform effecting?

**Comment by bvoisin** [comment]
Arg... indeed, here is a modified plunker that shows the scrolling problem @qmy777 just pointed out: http://plnkr.co/edit/T4xUE60QvH8gxuJE31o4?p=preview  

just scroll down.

I will look into it in the coming days.

**Comment by qmy777** [comment]
@bvoisin

**Comment by qmy777** [comment]
@bvoisin 
The scrolling row of ui-grid had the transform style, which effected the position style of the row. When div.ui-grid-row is scrolling, this element will be added the transform style, and it will have an effect like position: relative, therefore, the next row will cover the previous row! In order to solve this problem, i change the style by using `ng-class`, and change the template of 'ui-grid/uiGridViewport':
http://plnkr.co/edit/Ze6axa9GljdTpEcfYkIb?p=preview

This way just can solve the scrolling problem on the surface. I don't know whether there has other way to solve it or perfect way~

**Comment by bvoisin** [comment]
Looks good. I will adapt my code with your changes. Thanks
