### ISSUE TITLE
3.0 provide a single filter for the entire grid

### ISSUE THREAD

**Issue by qorsmond** [angular-ui/ng-grid#1765]
Wow first off thanks for this awesome data grid! Loving the new features.

I have a use case where the ui is primarily driven by one search box external to the grid, where I used to use the filterOptions to set up the filters.

As far as I can tell that is no longer available as the filtering is only available on the columns in the grid.

Is there any way to get the filters to work with an external input? I came across the rowSearcher service but I am not sure how to hook it up in the controller.

Any guidance will be much appreciated.

**Comment by aborchew** [comment]
@Hoakie 's solution was massively helpful for me. For my use case, we wanted out users to be able to search for rendered content - not necessarily the actual data that was being returned. Specifically, data that was being manipulated by a `cellFilter` parameter in a column config. Based on the mentioned solution, I created [this plnkr](http://plnkr.co/edit/jhQXJS9Rzz5hEIOlokh0?p=preview). Hopefully it's useful someone!

**Comment by thomas-koch-comsolit** [comment]
This might be related to #2796. Can we have a 'filter' label please?

**Comment by marc-rutkowski** [comment]
My own enhancement of @aborchew and @Hoakie solution to avoid error when using cellFilter with parameters (i.e. " date: 'yyyy' ")

[Plnkr](http://plnkr.co/edit/Iebryw7zTLQwwjvZWMnB?p=preview)

**Comment by pedroclayman** [comment]
All solutions that manipulate the data array directly have one downside...

1) Select some rows (multiselect)
2) set the filter so that those rows are not visible (what happens in reality is that those entries are being removed from the data collection)
3) clear the filter again which makes those rows appear again (the entities are being added again into the collection)
4) the rows are not selected anymore

It is of course perfectly clear why this happens but it is not really very user friendly. The column filter works as expected because it does not manipulate the data collection but simply makes the rows not visible.

The thing with selections and filtering gets even more interesting when we think of scenarious when the data is not present entirely, e.g. paging or infinte scroll.

It would make sense to keep a collection of selected entities but those entities do not have to exist in the whole data collection.

**Comment by W-prog** [comment]
Hello, great tips!
This plunker works very well
http://plnkr.co/edit/ijjzLX3jN7zWBvc5sdnQ?p=preview

Could you tel me if i can combinate with the accent_fold lib ?
https://github.com/aristus/accent-folding

For filter with remove Accent ? And your tips will be very very great

**Comment by aborchew** [comment]
There's no reason you wouldn't be able to, @W-prog. Just include `accent-fold.js` or wrap it in an Angular filter. Then extend the `while` funtion on line 34 of the plunkr you mentioned to call either `accent_fold` or your $filter.
