### ISSUE TITLE
Height calculation based on minRowsToShow ignores height of header

### ISSUE THREAD

**Issue by derrabus** [angular-ui/ng-grid#1873]
Encountered with 3.0 RC12.

If I don't explicitly set a height on the grid and set the option minRowsToShow to let's say `10`, I would expect to see ten records before I need to scroll down the grid. But instead I only see nine or even less, depending on the height of the header row and the horizontal scrollbar if displayed.

The height of the complete grid element is obviously set to `minRowsToShow * rowHeight`, ignoring the height of the header row.

**Comment by c0bra** [comment]
The height of the header row is unavailable until it is rendered as it is affected by things like the present of filter fields.

What we would have to do is somehow queue up a one-time recalc after the header is fully rendered, in the case that we do not have a fixed height. "Fully" is the key word here because column defs can be provided asynchronously, which means the header height could change... But then again no column defs could be provided and we' d never know whether or not they would be, so... I don't think this is really robustly doable.

Maybe we can just recalc the grid height once if the column defs are present at that time.

**Comment by c0bra** [comment]
This is working fine now.
