### ISSUE TITLE
Resizing a grid window shudders down the page with pinned columns

### ISSUE THREAD

**Issue by morungos** [angular-ui/ng-grid#1957]
When there's a pinned column and the grid has width 100%, the non-pinned part flickers between the alongside and below the pinned part. In some cases, it even sticks in the broken position, where the two viewports remain disconnected.

To reproduce, see the jsfiddle: http://jsfiddle.net/14mLg0aw/embedded/result/. Make the window smaller to see the effect. Key factors issues are the "width: 100%" CSS and the use of pinned columns. Sadly the full width is a requirement, but workarounds to achieve this effect would be welcome. 

This is the same on Chrome, Safari, and Firefox (all tested on OSX). 

It's possible that this is related to #1426, but I don't think so (unlike that issue, this also happens on Mac Firefox).

**Comment by PaulL1** [comment]
I think this is probably down to digest cycles, and the browser resizing before ui-grid gets time to change column widths.  I'm not sure I have a great answer as to how to resolve it.

**Comment by PaulL1** [comment]
OK, worked through this some more.  The issue looks to be that we're using `queueRefresh()` in the resize.  This means that we complete the digest cycle, then resize the grid in a timeout afterwards.  I surmise that this gives the browser time to draw the grid incorrectly, then in the timeout we fix it, causing the juddering.

I've fixed by changing to a grid.refreshCanvas immediately, rather than queueing the refresh.  This makes sense to me because there should be nothing else running in a resize digest cycle, so there's no reason there would be a performance benefit from debouncing the refresh calls when handling this event.

**Comment by PaulL1** [comment]
Looks like this isn't resolved - it worked on my test case, but not on the plunker (once the code was merged).

**Comment by PaulL1** [comment]
Wrong issue.  :-(

**Comment by PaulL1** [comment]
Same jsfiddle but in a plunker so that I can include a new ui-grid version.  I've made changes, which I had hoped would fix things.  They seem to make it a bit better, but I think we're still fundamentally stuck with needing a digest cycle before the grid resizes itself to the available space, and in the meantime the browser renders the sizing that it already had.

http://plnkr.co/edit/sm8AuildYJVl9Kk6rcek?p=preview

**Comment by sebilozano** [comment]
Was this ever resolved? I have different grids in tabs and am currently using 'ui-grid-auto-resize' to resize when shown. Each of these grids has a column pinned on the right and sometimes when I load the grids, the pinned column begins to flicker. Any ideas?
