### ISSUE TITLE
"Visible" property in columnDefs does not affect the grid appearance

### ISSUE THREAD

**Issue by onkami** [angular-ui/ng-grid#2046]
According to e.g. this example http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns the columnDefs object is watched and its changes are reflected in the grid on screen.

However when I change visibility property in a columnDefs element, this is not reflected at all. Only adding/deleting entire element of columnDefs works. It means that simple showing/hiding columns is not really an option, you have to keep separate object of "all" columns and "visible" ones, convert one from another at all times when changes are done,  and feed latter to UI Grid.

**Comment by jamescarter-le** [comment]
This is an important issue for writing dynamic filters outside of the ui-grid.

ui-grid should allow watch to be a reference to a $scope variable.

In the mean time, I made ui-grid perform a deep watch on the columnDefs collection instead of the shallow watch which happens as a result of using $watchCollection. This means I can update the columnDef visible property in my controller scope $watch function and it will refresh the grid automatically.

To achieve this change:
var columnDefWatchCollectionDereg = $scope.$parent.$watchCollection(function() { return $scope.uiGrid.columnDefs; }, columnDefsWatchFunction);
To:
var columnDefWatchCollectionDereg = $scope.$parent.$watch(function() { return $scope.uiGrid.columnDefs; }, columnDefsWatchFunction, true);

**Comment by PaulL1** [comment]
The tutorial: http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns has a "toggle visible" button, which demonstrates how to make this dynamic.
