### ISSUE TITLE
Move columns not working well on touch devices

### ISSUE THREAD

**Issue by jpuri** [angular-ui/ng-grid#2303]
In grids with huge horizontal scroll the moved columns ar e not getting repositioned correctly. I am working on this issue.

**Comment by jpuri** [comment]
Hi,

I am now working to fix this up.

**Comment by jpuri** [comment]
I was trying to use touchEvents (touchstart, touchmove and touchend/ touchcancel). Strange but fact is that touchend after touchmove is not well supported by most of touch devices.

http://stackoverflow.com/questions/11314185/multiple-touches-touchend-event-fired-only-when-a-touchmove-occurs

I am not very sure how can we implement this feature on touch devices. @PaulL1 any suggestion ?

**Comment by PaulL1** [comment]
Absolutely no idea.  :-)  I do know that we need to be careful that just because devices support touch events doesn't mean that they don't also have a mouse - we have a few issues with laptops that are touch enabled but people are trying to use a mouse on them and it's not working.

I think if we're going to try to do this on touch devices we need to write down what semantics we want for each of the touch events on a header.  Because we're trying to do sort, menu open and drag all at the same time, and I'm not sure there's enough touch events to do all of them.

**Comment by jpuri** [comment]
The issue appears to be that different devices are firing different events, but yes its true that our column headers have a lot of events to handle.

@swalters once suggested to implement move columns differently. I am not very sure might be we can come up with a better design for move columns. I have time these days to do any changes or fix issues.

**Comment by jpuri** [comment]
Might be in our docs/ tutorials we can mentions which features will/ will not work with touch devices.

**Comment by PaulL1** [comment]
@jpuri, I think #3142 will fix this.  At least it does on my iPad, not sure about other touch enabled devices.  Do you want to test it out?

**Comment by PaulL1** [comment]
I think this is resolved.  Closing.
