### ISSUE TITLE
Move column functionality - moving column does not shows up in IE

### ISSUE THREAD

**Issue by jpuri** [angular-ui/ng-grid#2352]
Although the moving column repositions correctly in IE but moving column is not seen (tested with latest version of IE: IE11).

**Comment by ChrisSchmidt1991** [comment]
This issue is related to css 
.movingColumn {
  position: fixed;
}
This needs to be changed to absolute. Even though this works for Firefox and Chrome, because it doesn't reference the browser window as it should. it might be related to or similar to http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/. 
The issue with changing it to absolute is it messes up the scrolling badly.

**Comment by AgDude** [comment]
@jpuri Is this still ocurring for you? I can't reproduce this.

**Comment by jpuri** [comment]
I did not tried this, but as I remember it has been fixed by some contributor.
