### ISSUE TITLE
Ui-Grid Horizontal Scroll is not working if Paging is enabled.

### ISSUE THREAD

**Issue by adityajk** [angular-ui/ng-grid#2465]
I have created a ui-grid and included the pagination to it. Now the pagination div is overriding the horizontal scroll and I am not able to scroll it.

<div id="grid1" ui-grid="gridOptions" ui-grid-paging class="grid"></div>
Please find the Plunker here - http://plnkr.co/edit/dVrkKF1G85F3e72BaUfi?p=preview

Remove the 'ui-grid-paging' from the div then the horizontal scroll is working fine.

I am using ui-grid - v3.0.0-RC.18.

**Comment by alexandery** [comment]
The way I see it - it's a problem with pagination styling and you'll have to fix that overriding the existing CSS styles. I'm in the same boat, but just didn't get around to fixing this issue. Not sure why this even made into the codebase since it's clearly a bug (which can be seen even on http://ui-grid.info/docs/#/tutorial/214_pagination).

**Comment by PaulL1** [comment]
Is this perhaps fixed from the recent scroll changes?

(On the question of how it made it into the code base, remember that not everyone uses the same OS and browser platform.  On my Mac and Chrome it is fine, but that's because Macs don't have scrollbars. Not that I wrote this bit of code, but I can see how the defect could be introduced)

**Comment by alexandery** [comment]
@PaulL1 Yes, it is better now. The styling of pagination plugin is still somewhat not ideal (the area it occupies is barely large enough to fit it), but the scrolling is now working.

**Comment by PaulL1** [comment]
OK, thanks.
