### ISSUE TITLE
Need raw filter term

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ng-grid#2475]
When implementing a custom filter, the search term is modified before being provided to the filter function. These modifications make it difficult or impossible to implement desired filtering logic.

There needs to be some way to get the "raw" term that the user typed in.  I think this should be the default behavior for all custom filters, but an option like "filterRaw:true" might be fine if needed for compatibility.

**Comment by axelstudios** [comment]
This caused problems for me as well until I [started searching through the code](https://github.com/angular-ui/ng-grid/blob/8f7ee4c7d861557b0ff188831c8cd2aec371c787/src/js/core/services/rowSearcher.js#L215) and saw that I just needed to use the escaped searchTerm in a RegExp constructor rather than doing any kind of substring matching.

Previously, my workaround was to strip backslashes from `searchTerm`, which worked great for everything except actual backslashes in the raw filter, but RegExp is the way to go.

**Comment by eirenik** [comment]
That would be fine if one's goal was to do exactly what the grid code does with filters, but the whole point of a custom filter is to do something different. Possibly extremely different.

The whole idea of extensibility is recognizing that you can't predict everything that will make sense for everyone and every possible application's data.  Maybe I want '@' to be a wildcard.  Maybe I want to append '5' to every 'k' in the filter.  Whatever it is, providing the raw input from the user is essential for permitting customization.

**Comment by PaulL1** [comment]
I can also mark this as a future enhancement, and happy to accept a pull request that adds this functionality.

At the moment the (quite small) development team are focusing their time on stability and reaching an initial release of 3.0, not new functionality.

**Comment by PaulL1** [comment]
We have provided the ability to define custom filter widgets and custom filter behaviour.  I think this should meet the needs here.
