### ISSUE TITLE
$http request

### ISSUE THREAD

**Issue by BrodaUa** [angular-ui/ng-grid#2478]
Hi guys! Can you help me with next problem. There are my code in controller below:
$http.get('data.json')
   .success(function(response){
    $scope.gridOptions.data=response;
})
But it doesn't work, cause my $http request runs after all code in controller. Some people says that as $http is async,so it takes some time to complete, but no....I cant undestand why this work how I describe :( As a result - when it finally goes through my request, and gridOptions.data initialize with response value, my grid doesn't show.
What I do wrong and how to solve this problem??

**Comment by c0bra** [comment]
Can you reproduce in a plunker? Our at least paste the rest of your controller code where you're setting up your grid?

**Comment by BrodaUa** [comment]
Sure, its here : http://plnkr.co/edit/93gYej9nXQyeffgDoHwF

**Comment by steverA** [comment]
I took a look at your code and you don't seem to have a directive that includes something like ui-grid="gridOptions" If you examine the elements after your code starts, there is nothing inside the div with the SimpleController. I suggest you look at some of the tutorial samples...

**Comment by BrodaUa** [comment]
I know, at first time there are no directives in my html page. But as I say before, when my code runs, I want to put the derectives into my block with id = "myHTML".  I try to get this point cause I needn’t to build only one grid, I need several grids. My directives initialize in factory, if you look there, you find it....

**Comment by steverA** [comment]
Okay, you forced me to look at it!  :-)
Your missing a bit of code in your html file... you never included ng-App="myApp" in any tag. If you do, your code starts to fire. I can't load the json file locally because it is a cross-site scripting problem - need to hit it on a server!

**Comment by BrodaUa** [comment]
Steve, yeah, I miss it in a plunker....but it okay on my server, and still doesn't work(

**Comment by swalters** [comment]
is your response object an array of properties?  whenever I use $http service, I must deserialize response.data.

 var rows =  angular.fromJson(response.data);

**Comment by steverA** [comment]
Last comment and then I have to get back to work.
Have you tried debugging this in a browser and added a .error function to the $http.get() ??

--

Stephen R. Alpert, PhD
Principal Technical Architect
GE Healthcare
Clinical Business Solutions

T +1 617 519 2216
F +1 617 519 2625
E steve.alpert@ge.com<blocked::mailto:steve.alpert@ge.com>
www.gehealthcare.com<http://www.gehealthcare.com>

         GE imagination at work

**Comment by BrodaUa** [comment]
Swalters, Steve, yes, of course I try to debug this, and I can't understand why it runs through all my code, without $http, and at the end through $http,  it seems to be "too late" to show my grids. Yes, it's an array of properties that I need, it takes the right value at the end! BUT it doesn't want to be shown. There are no errors, when I debugged.

**Comment by BrodaUa** [comment]
yeah, you are right....here an example of the same problem but without any unnecessary code : 
http://plnkr.co/edit/93gYej9nXQyeffgDoHwF

**Comment by steverA** [comment]
Per latest plunker, remember $http.get is a promise and won’t be done immediately but myFactory can be injected into myController.
The calls in myController:
                $scope[myFactory.getData()[0].name] will fail because there isn’t a 0th element yet, the $http hasn’t completed yet

--

Stephen R. Alpert, PhD
Principal Technical Architect
GE Healthcare
Clinical Business Solutions

T +1 617 519 2216
F +1 617 519 2625
E steve.alpert@ge.com<blocked::mailto:steve.alpert@ge.com>
www.gehealthcare.com<http://www.gehealthcare.com>

         GE imagination at work

**Comment by BrodaUa** [comment]
I agree, Steve, that $http.get need some time to be complete. I update the plunker example.....

**Comment by PaulL1** [comment]
I think that the problem here is in your code @BrodaUa, there is a lot of stuff going on that just looks wrong.  When I edit your plunker to remove things that aren't related to the grid, it works fine.  http://plnkr.co/edit/LQs43fKkWgrXTtWwU5Z9?p=preview

Things I can see are:
1. You're doing an http get to retrieve your configuration, this returns `{ name: xxx, data: xxxx}`.  You then create a new object, and put the response into it: `{ name: yyy, data:[ ...] }`.  This will result in `{ name: xxx, data: { name: yyy, data: [ ... ] } }`.  I don't think this will ever work
2. In simplifying your code, you've left stuff out, such as ever assigning anything to gridOptions
3. I'm not sure that dynamically creating the div is working the way you think it is, when I remove that code and just put the div into the html it works fine.

I'd suggest working through your code and making sure that every variable has the data in it that you think it does.  I also generally recommend indenting your code properly when you create a plunker, it makes it far easier to read and to give you support.
