### ISSUE TITLE
Expandable grid needs ability to hide the expandable column and control it programmatically

### ISSUE THREAD

**Issue by majgis** [angular-ui/ng-grid#2504]
When using the expandable grid with deep nesting, the horizontal space is quickly taken up by the expandable button columns.

Potential solution:
Add an option to hide the expandable column and allow for expansion to be controlled from the row template.

**Comment by majgis** [comment]
Digging a little deeper, it looks like controlling the row expansion from a custom row template is easy enough:

     ng-click="grid.api.expandable.toggleRowExpansion(row.entity)"

We just need the ability to hide the expandable column.

**Comment by PaulL1** [comment]
I believe that grouping and treeView provide more reasonable means to create deep nesting - I am assuming that use cases with deep nesting are more along the lines that those features provide.  Closing.

**Comment by FlavorScape** [comment]
I've been struggling to hide this column. Modifying the or removing the header cell does nothing. It's a useless column (you do not need a button to expand a row). I've tried ng-if="col.name !== 'expandableButton'" but it turns out you have to delete the entire rowgroup before it disappears, and this is not an option from within the row template itself.

**Comment by FlavorScape** [comment]
Honestly I think the column should just be removed from the API and replaced with instructions to add a button yourself. the code for expand row would be fine. I think everyone understands ng-click, and nobody is going to use the default styling. I've never seen any designer hand me plus icons.

**Comment by FlavorScape** [comment]
Ah, ok. Sorry for all the posts: There is a CSS way to do it. Though, this is somewhat brittle solution (in the advent the API changes. This CSS may not be applicable in the future, since it's not configured through the API. 

  .ui-grid-expandable-buttons-cell,.ui-grid-pinned-container.ui-grid-pinned-container-left {
    display:none;
  }
