### ISSUE TITLE
rowEdit.on.saveRow Not called after editing cell and navigating to other cell on same row

### ISSUE THREAD

**Issue by martysupple** [angular-ui/ng-grid#2515]
I have a grid where only 1 cell is editable. When I make a change then navigate to another cell on the same row (which is not editable) the saveRow event handler is never called.
It seems that the navigate function is cancelling the timer and not setting it back since we are on the same row.

        navigate: function (newRowCol, oldRowCol) {
          var grid = this.grid;
          if (newRowCol.row.rowEditSaveTimer) {
            service.cancelTimer( grid, newRowCol.row );
          }

          if (oldRowCol && oldRowCol.row && oldRowCol.row !== newRowCol.row) {
              console.log("navigate setting timer back on");
            service.considerSetTimer( grid, oldRowCol.row );
          }
        }

**Comment by PaulL1** [comment]
Correct, this is exactly expected behaviour.  RowEdit only saves the row once you leave it and don't return for at least a few seconds - which is intended to deal with situations where multiple cells in the row are editable, and you edit each of them (the aim is to not get save errors if the user hasn't yet filled in mandatory fields, and to avoid saving multiple times when the user is making a series of changes to a row).

I don't think there's a good way around it - if you want to save simply on cell exit then it'd be easier to just listen to the cellEdit event and save whenever that is triggered.

**Comment by martysupple** [comment]
Thanks Paul, in order to solve for the user navigating off the page before
the async save is posted after the default 2 seconds, I had to call
flushdirtyrows in the window.onbeforeunload anyway, this will help make
sure these edits are saved as well..thanks.

Marty Supple

**Comment by PaulL1** [comment]
OK, that sounds reasonable - that's an expected usage as well (in my application I call flush dirty on navigation as well).
