### ISSUE TITLE
Different data on same grid 

### ISSUE THREAD

**Issue by 32teeths** [angular-ui/ng-grid#2522]
For a project i am working on i have maintained One grid , and for each data from the back end replaced in the same grid  . The grid works fine for the first time whichever data it is , but for the second time there is some problem with the css or the template . Here is the link for the plunker . http://plnkr.co/edit/YUxYL7DXi2MX6B8UsEfO?p=preview

**Comment by juliusakula** [comment]
Check this out: http://plnkr.co/edit/OFt86knctJxcbtf2MwYI?p=preview

**Comment by 32teeths** [comment]
@juliusakula : Thank you for your response . I have seen that example earlier . And I double checked my plunker . It's working . It takes a little time initially to load ,  But is working fine . Could you please check it once again . I dont understand what I am missing out here ,

**Comment by PaulL1** [comment]
I think it's to do with the way you're manipulating the columnDefs, although I'm not quite sure why it's causing the formatting problems.  

I've linked to the current master version, rather than including ui-grid.js as a plunker file (which also makes it run faster), and tidied the code a bit to simplify.  This one is sort of working (you have to click swap data twice, not quite sure why), but might give you some pointers to a diagnosis.

http://plnkr.co/edit/O7Uhae8kbMrLZOf4QurF?p=preview

**Comment by 32teeths** [comment]
I checked the source code and found out that , all the columns (elements) are generated but the css for some particular fields are not present . In this case , the css for the column that repeats is not set . Why is that ?

**Comment by 32teeths** [comment]
Instead of specifying {field:'field-name'} , I specified {'name':'field-name '} and it was working fine . I am not sure  , what can possibly be the reason , Thank You anyways.

**Comment by alexandery** [comment]
@32teeths - check the thread https://github.com/angular-ui/ng-grid/issues/2193 - I've posted some code there that fixes an issue of column replacing for me.

**Comment by PaulL1** [comment]
OK, sounds like there is a resolution to this, and no new comments for 3 weeks.  Closing.
