### ISSUE TITLE
sets priorities to 0 when clicked to sort and overrides initial priorities

### ISSUE THREAD

**Issue by ilyalopatkin** [angular-ui/ng-grid#2524]
When set "suppressRemoveSort: true", all the columns get reported in the sortChanged callback, and all priorities are eventually set to 0 when clicked through them, so I can't find a way to tell which column was clicked last.

The eventual goal is to set the highest (0) priority to the recently clicked column, and sort the rest according to their initial priorities.

Example: we have three columns Name, Gender, Company. The default priorities are 0, 1, 2 accordingly. Clicking on Gender should change the priorities to 1, 0, 2. Clicking on Company should change them to 1, 2, 0. Sorting should always be on.

Is this possible to do at all?
Plunker: http://plnkr.co/edit/iarrHs?p=preview
Try clicking on headers and see console for column sort data

**Comment by PaulL1** [comment]
I don't think that's the way that priorities work.  In general you need to shift-click or click on the sorts in order to set priority.  But the priority can't be changed if you can't remove sort, I guess other than shift-clicking.

If you want to support this use case, I think you'd probably have to write a custom directive that layers on top of the header cell and takes custom action based on the click event (that custom action being to reorder the sort priorities).

**Comment by ilyalopatkin** [comment]
Thanks Paul. We're looking at two solutions now the first being a custom click handler as you suggested, the other is overriding priorities in the sortChanged callback. If we set suppressRemoveSort=false then we are able to detect which column we have clicked last which serves as a kind of a click handler. If not one then the other way should do. Thanks again!
