### ISSUE TITLE
Limit of data to do pdf export?

### ISSUE THREAD

**Issue by bayy** [angular-ui/ng-grid#2529]
I have 1300+ rows in a grid, and I have experienced browser crash when using             `$scope.gridApi.exporter.pdfExport( uiGridExporterConstants.ALL, uiGridExporterConstants.ALL );`
 to export data to a pdf file. 

![image](https://cloud.githubusercontent.com/assets/2373656/5690433/383cf21a-9846-11e4-95f4-d10df73bdc07.png)

csvExport works fine with the same data.

Any suggestions? Is there limit of data on pdfExport?

**Comment by PaulL1** [comment]
pdf export is based around the pdfMake library.  It is possible that the library has limitations that we're not aware of.  Do you have information on where the error occurred - perhaps a console error that identifies a line of code?

**Comment by bayy** [comment]
As the browser crashed, there is no error info at all. I will poke around to see whether I could get some info.

**Comment by PaulL1** [comment]
I think this is a limitation in the underlying pdfMake library, and I don't think there's anything we can do with that.  Suggest pushing upstream to the author of that library.

**Comment by AgDude** [comment]
I realize this issue is closed, but here is a little more info. This is related to https://github.com/bpampuch/pdfmake/issues/275

Here is a plunker forked from the export demo: http://plnkr.co/edit/HAEvot?p=preview
Chrome crashes or silently fails with only 200 rows. Firefox handles 1000 without a problem.
