### ISSUE TITLE
stable sort

### ISSUE THREAD

**Issue by trokohl** [angular-ui/ng-grid#2534]
I'm not sure how the sorting of the grid internaly work, but i suppose it use the sort function of the browser.
The ECMA Script specification does not specify which algorithm has to be used or if the algoriothm should be stable. So the sort of the grid is not stable is all browsers.

An example:
Open http://ui-grid.info/docs/#/tutorial/103_filtering in Firefox an sort the filtered Gender column(all male).
Toggle the sort order of this column and nothing will happened.

Try the same in Chrome, which implements an non stable sort-function.
=> the order of the columns changed 

Any idea to make it easily stable in ui-grid?

I have 2 proposal to solve this problem:

1. own sorting algorithm
2. a way to define a second static sorting column, an id for example

**Comment by trokohl** [comment]
i found a quick workaround for me:

            $scope.gridApi.core.on.sortChanged($scope, function (grid, sortColumns) {
                $scope.rows.mergeSort(function(a, b) {
                    return $scope.gridApi.core.sortHandleNulls(a, b);
                  });
            });

with a stable sort algorithm like merksort from here
https://stackoverflow.com/questions/1427608/fast-stable-sorting-algorithm-implementation-in-javascript

**Comment by PaulL1** [comment]
Right, so I've had a look.  I hadn't come across stable sorts v's unstable sorts before, but basically a stable sort is one in which you don't change the order of things that "appear the same".  So in your example above, if we sort on a column that is already filtered to be all 'male' then nothing should move around, but in Chrome it does because Chrome doesn't have a stable sort.

The way around this is to use a custom sort, but we probably don't want to do that - it's much easier to just use the browser sort.  (To put it another way, we could say "that's a Chrome bug, go log it with them").  Another option is to allow the user to provide us their favourite sort algorithm if they don't like to rely on the browser sort (and I think this would make more sense).

Some background reading on sorting: http://blog.rodneyrehm.de/archives/14-Sorting-Were-Doing-It-Wrong.html (it also suggests some multi-lingual stuff that we aren't doing either).

**Comment by PaulL1** [comment]
I've chosen to follow https://adamfowlerml.wordpress.com/2013/04/02/stable-sorting-in-javascript/, and basically extend our sort routine to return a sort based on the old index if the two values are equal.
