### ISSUE TITLE
Horizontal scrollbar overlays last row when there is a pinned left container

### ISSUE THREAD

**Issue by romcode** [angular-ui/ng-grid#2540]
Hi ,
When i have a row pinned the horizontal scroll on the rest of the columns is displayed on top of the last row, and the vertical scroll it never gets to the end.
i'm using  ui-grid - v3.0.0-RC.18-5602b87 - 2015-01-12
here is the plunker with the example
http://plnkr.co/edit/0lcUyIdgRSGj8Yw0oC8j?p=preview

**Comment by PaulL1** [comment]
I think @swalters is working on this at the moment (and may have committed a change yesterday that addressed it).

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.

**Comment by romcode** [comment]
Hi @PaulL1 . I saw you have closed this bug , but it's stil happening .
Please scroll to the bottom.
http://plnkr.co/edit/2110dO8HjAe7xfMDCQ5B?p=preview

**Comment by PaulL1** [comment]
It's not doing it for me, but I'm on a Mac so I don't really get scrollbars.

What do you mean by "on scroll, not directly drag"?

**Comment by romcode** [comment]
I mean that it's not working when i wheel scroll to the bottom of the grid, but when i go with the mouse on top of the scroll tab and drag it , it shows the entire row.

**Comment by PaulL1** [comment]
It's working fine for me on Chrome/OSX.  http://plnkr.co/edit/D179b48Tl3RdphjKEvtl?p=preview, and Safari OSX.

**Comment by romcode** [comment]
It looks like this:
![gridissue](https://cloud.githubusercontent.com/assets/8833239/5997291/e0edadf4-aac1-11e4-9b99-de5d6f8b3bad.jpg)
I'm on Chrome/ Windows.

**Comment by PaulL1** [comment]
OK, that's different from not getting to the end.  That's the horizontal scroll bar overlaying the last row.  Thanks for the screenshot.

**Comment by PaulL1** [comment]
@swalters: do your latest changes address this?

**Comment by c0bra** [comment]
Definitely looks like a scrolll event race condition between the render containers.

**Comment by c0bra** [comment]
What I'm seeing currently is, with infinite scroll enabled, when I scroll to the end and all data is loaded, the grid jumps back up maybe 6-7 rows. It will do this each time I scroll to the end.

**Comment by PaulL1** [comment]
Ugh.  That'll be my fault.  The infinite scroll scrolling logic was a bit tricky - I rewrote that section because I wanted a smoother scrolling experience.  The logic is basically driven by rows - if you have 100 rows and you're at (or near) the bottom, you're about 95% scrolled.  If we trigger a get and add another 100 rows, we have to calculate where to move the scroll to so that the scroll is in about the same place, remembering we might have a bit of momentum as well so maybe by the time we process it we're at 98% not 95%.

Furthermore, relating rows to scroll% is hard.  Row 0 at the top corresponds to 0%, but row 100 never gets to the top - it's about row 90 that's at the top when we're 100%.  

I'm not all that thrilled with the code I wrote to try to unpick this, but it mostly worked (and was better than what was there before).  But it definitely shouldn't jump when no more data is loaded - unless perhaps the user hasn't set the "no more data down" flag, and so the logic thinks they loaded data.

Hmmm.  Let me look at the plunker.

**Comment by PaulL1** [comment]
Yeah, that plunker is using the old api for interacting with infinite scroll.  The tutorial shows the newer way to do it.  I can fix it with this change: http://plnkr.co/edit/D179b48Tl3RdphjKEvtl?p=preview (passing false to both scrollUp and scrollDown once we get data), but that's not really doing it properly, you're supposed to calculate whether there are any more pages and then tell infinite scroll whether or not to keep raising events.

**Comment by romcode** [comment]
Made the changes as suggested and all seems to work fine .
Thanks.

**Comment by c0bra** [comment]
Alright I'll close then. Thanks guys.
