### ISSUE TITLE
Question about cellClass

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2580]
In the 1/15 build of 3.0rc18, I've observed in the on.navigate function
1. if a column does NOT have a cellClass function defined, the newRowCol.col has a property cellClass = ""
2. if a column DOES have a cellClass function defined, the newRowCol.col has a cellClass function.

Is there any way to find the "value" returned by the cellClass when the function was originally invoked without having to call it again? I can see in the debugger that the div with class ui-grid-cell that wraps the div with class ui-grid-cell-contents has the return value of the cellClass.

![blue](https://cloud.githubusercontent.com/assets/9431902/5784258/8804dd1a-9d98-11e4-81eb-22cafe5aa6e1.png)
You can see it in this plnkr: http://plnkr.co/edit/Cf8Cy3VOnQKl2Fk7UZ3X?p=preview
Right now, I'm using an ng-Style to overload what I want but that gets evaluated on every $digest.

**Comment by PaulL1** [comment]
I'm not clear entirely what you're seeking.  Are you looking to add to the cellClass, and you want to retain what's already there but add some extra of your own?  Is there a reason you couldn't put that inside the cellClass function itself?

On the gridRow, for selection and rowEdit, we did some fiddling so that they didn't overwrite the class (i.e. a row could be both selected and dirty, as an example).  So you could look at that code if you wanted to stack on top of the cell directive, but I'm not entirely clear why you'd want to do that.

**Comment by steverA** [comment]
Simply, when I'm in the in the gridApi.cellNav.on.navigate() and am handed newRowCol, I was hoping the value determined by the cellClass callback would be available on the newRowCol.col so I could easily test it rather than invoke the function again. I could then react differently if (for example) the cell was blue!

**Comment by PaulL1** [comment]
In ui-grid-cell.js there is record made of the class that was added, but it's in a local variable `classAdded`.  What I'm not sure of is how we'd provide a means to access that - there isn't a good way to get at a specific cell via the API.  It certainly couldn't be on the col, since it's one per cell.

**Comment by c0bra** [comment]
Is your cell-class function high-cost? If so, could you memoize it or cache it on your end somehow? That would take the responsibility out of the grid's hands.

**Comment by steverA** [comment]
Not sure what you mean my memorize it. What I did do is in the cellClass testing, I added an attribute to the col entity if my condition was true. in the cellNav, I check that first and it eliminates a lot of false testing that would have taken more work.

**Comment by c0bra** [comment]
Memoization  is caching function output so subsequent calls with the same arguments return the same value without having to do costly calculations.

**Comment by c0bra** [comment]
No updates in > 2 weeks so I'm going to close. @steverA if you're still looking for a way to access to data specific to a cell element from inside a navigate() handler then we'll probably want to open a new issue since that has much broader scope and would take a lot more work.
