### ISSUE TITLE
There is no grid option to display a message if the grid is empty

### ISSUE THREAD

**Issue by msosa** [angular-ui/ng-grid#2597]
Hey guys, so there doesn't seem to be an easy option to display a message in the event of an empty grid.  I was able to use the directive below which I got from https://github.com/angular-ui/ng-grid/issues/496.  But that seemed to have been closed because it was a 2.x problem.  Do you think a functionality like this could be added?

```javascript
	.directive('showEmptyMsg', function ($compile, $timeout) {
	    return {
	        restrict: 'A',
	        link: function (scope, element, attrs) {
	            var msg = (attrs.showEmptyMsg) ? attrs.showEmptyMsg : 'Nothing to display';
	            var template = "<p ng-hide='data.length'><b>" + msg + "</b></p>";
	            var tmpl = angular.element(template);
	            $compile(tmpl)(scope);
	            $timeout(function () {
	                element.find('.ui-grid-viewport').append(tmpl);
	            }, 0);
	        }
	    };
	})
```

**Comment by PaulL1** [comment]
I think it could be added, but it would probably be a new feature.  It is a little tricky for the grid to know the difference between "empty still getting data" and "empty there will be no data", because the grid doesn't control the retrieve of data.  For this reason you'd usually implement a spinner or empty message outside the grid.  But plausibly the grid could have the message logic itself, and then the user could call the grid to tell it that they had retrieved their data and it was empty.

**Comment by c0bra** [comment]
You can transclude anything you want into the grid. Here's a plunker showing how to do a "No Rows" message: http://plnkr.co/edit/156wBdD5ogLGcKamP3lJ?p=preview

**Comment by msosa** [comment]
I see what you're saying Paul, sometimes it can take a few seconds for the data to return so the empty message will still be there even if there is data still coming in.  I currently have an empty message as well as a spinner, but without the spinner I could see the user getting confused.  But yeah what suggest will work, maybe have the user call the grid before and after the data is retrieved.

Thanks c0bra! I have implemented something similar to what you suggested

**Comment by PaulL1** [comment]
Excellent, I'll close then.

**Comment by jamespsterling** [comment]
@c0bra much appreciated!
