### ISSUE TITLE
Enable/Disable cellNav and allow row selection when disabled

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2612]
We enable/disable all our cells based on an external scope like so:

cellEditableCondition: function ($scope) {return $scope.getExternalScopes().view.isEditing;},

We want to disable cellNav when isEditing is false and allow row selection. How do we achieve this?

**Comment by smithscripts** [comment]
Would it be possible to add a "allowCellFocusCondition". This would solve my problem with toggling in and out of edit mode. I would then get row select behavior in non-edit mode and cell select behavior in edit mode. Like so:

    allowCellFocus: function ($scope) {
                return $scope.col.grid.appScope.view.isEditing;
            },

**Comment by PaulL1** [comment]
A lot of the grid functions aren't quite so dynamic as you're imagining - cellNav is generally present or not present.

However, the way you describe it, I sort of get the impression that `isEditing` might be for the whole page, rather than some sort of row by row thing.  If that's the case, then you're really talking about turning cellNav and row select on and off for the whole grid.  If so, I'd use `gridOptions.enableCellNav` and `gridOptions.enableEditing` when you first render the page.

**Comment by PaulL1** [comment]
Possible solution offered, no response for some time, assuming raiser has resolved their issue and closing.

**Comment by ncourtial** [comment]
Hi,
+1 for gridOptions.enableCellNav in order to disable it programmatically.

**Comment by pjwalmsley** [comment]
+1 for gridOptions.enableCellNav in order to disable it programmatically.
