### ISSUE TITLE
Improve default sorting

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#2617]
The default sort function appears to be ```rowsorter.sortAlpha```. Currently this function throws an error if there is a number in the column, because it calls ```toLowerCase```. The simplest solution to this would be to call ```a.toString().toLowerCase()``` instead.

I am suggesting to take it a step further, and if both a and b numbers, actually sort them as numbers.

**Comment by AgDude** [comment]
I just came across this sort function in some of my other code, and thought I would put it here for an example. It could be cleaned up with a few less ifs.

```
      if ( !isNaN(intA) && ! isNaN(intB) ){
        // sort as numbers
        return intA - intB;
      }
      // put numbers first
      else if ( !isNaN(intA) ){
        return -1;
      }
      else if ( !isNaN(intB) ){
        return 1;
      }
     // sort as strings
      if ( a[sortProp].toLowerCase() > b[sortProp].toLowerCase() ){ return 1; }
      if ( a[sortProp].toLowerCase() < b[sortProp].toLowerCase() ){ return -1; }
      return 0;

```

**Comment by PaulL1** [comment]
The general expectation is that all elements in a column have a like type, so the grid sorter guesses the column type by looking at the first element.  If you want more specific behaviour you could provide a custom sort function for that column.

I think I can modify it to do the `toString`, because errors are bad.  But I'm not sure I want to modify the alpha sorter to start doing numbers as well.

**Comment by AgDude** [comment]
Thanks paul. I didn't realize it was picking a sorter based on content.
