### ISSUE TITLE
Cell Background Color

### ISSUE THREAD

**Issue by flex123** [angular-ui/ng-grid#2645]
Hello,

I have a requirement where the background color of a cell must be set according to the hexadecimal value of a field in the grid data.  It works pretty well until I do a vertical scrolling.  If you look at the following screenshot, you will notice that the background colors for Color 9 to Color 15 in the first table do not match with the background colors for the same cells in the second table.  The issue in the first table only happens after the table is scrolled vertically.  Do you have any suggestion on how to work around this issue? Thank you...

The plunker that shows the issue can be found at:  http://plnkr.co/edit/N0btQ8btjgQXoRk6R0Zy?p=preview

![image](https://cloud.githubusercontent.com/assets/10717743/5913421/26747624-a5b2-11e4-9580-65b2fd73255c.png)

**Comment by PaulL1** [comment]
The most likely workaround is to call notifyDataChange(), on the grid.api.core.  But I'm not sure that you should have to - it should be automatic.

**Comment by flex123** [comment]
Thanks Paul.. Do you think this is a bug?

**Comment by PaulL1** [comment]
It may be - a sample plunker would help to check that.  The row virtualisation means that when you scroll we change the data that each cell points at.  The cellClass functions should re-evaluate when we do that, so in concept it should automatically calculate.  But I'd need to see what else is going on.

I probably should have asked what version you're on.  There were some fixes went in recently on this, so potentially try upgrading to at least RC18, perhaps build from source to see if that addresses it for you.  (A plunker would also sort that out - because if it doesn't do it in the plunker it's probably the newer code - plunkers usually use the unstable build).

**Comment by flex123** [comment]
Thanks again..  I do have a sample plunker with a table that requires scrolling and one that doesn't so that I can compare the colors.  The one that requires scrolling is problematic.

http://plnkr.co/edit/N0btQ8btjgQXoRk6R0Zy?p=preview

**Comment by flex123** [comment]
I made a mistake by using ng-style instead if style when setting the background color of a cell.  The issue is resolved now.

http://plnkr.co/edit/N0btQ8btjgQXoRk6R0Zy?p=preview
