### ISSUE TITLE
rowHeight: 'auto' affect only one column

### ISSUE THREAD

**Issue by javid-p84** [angular-ui/ng-grid#2656]
by setting rowHeight: 'auto', I expect the whole row will be the size of the tallest (biggest) cell in the row.  however, different cells will have different heights! not consistent look

**Comment by jpuri** [comment]
I checked http://ui-grid.info/docs/#/tutorial/114_row_header, and could not find a property like 'rowHeader'.

Can you please share your code, preferably in a plunkr.

**Comment by javid-p84** [comment]
Sorry, I meant rowHeight. just edited that.

**Comment by javid-p84** [comment]
Here is the plunker. http://plnkr.co/edit/9Ndmv6R0ebWWNN6Ab3yz?p=preview
Please note the borders and backgrounds...

**Comment by jpuri** [comment]
@javid-p84 ,

ui-grid does not supports value 'auto' for rowHeight. It can only take numeric values.
@PaulL1 , should we extend our code to support 'auto' value for rowHeight.

**Comment by PaulL1** [comment]
If it's not currently a feature, I'm not sure it's a priority to add it.  I have some concern about how we'd even calculate it - the nature of row virtualisation means that we cannot find the tallest row, as we're only rendering the first few.  I think it was a conscious decision to require a fixed row height.

**Comment by javid-p84** [comment]
@PaulL1 & @jpuri 

There are many cases in which the rows need to have different heights, depending on the size of the data that they are displaying in each cell. Unfortunately, I have a lot of these cases in my current project. Do you guys think that this issue will be addressed?

**Comment by PaulL1** [comment]
No, I don't believe so.  It's an explicit design direction of the grid that all rows must have the same height.  One of the big features of the grid is the row virtualisation, which means that we don't render rows until they scroll into view.  We cannot calculate the height of a row if it's not rendered.

**Comment by javid-p84** [comment]
Whenever a row is rendered, If we could set the height in ui-grid-row class to auto and all the ui-grid-cell div's height to 100% might help to render them. I don't think they need to be calculated by js, but the browser will take care of all the cell divs in a row (expand the short ones). Anyway thanks for your replies and considerations. Unfortunately we have to switch to another grid that can support rows with different heights. keep up the good work.

**Comment by PaulL1** [comment]
The problem here is the virtualised scrolling.  To calculate and render the position within the scroll bar we need to know the total height of the canvas.  To know the total height of the canvas you need to either render all the rows and add them together, or require a fixed row height that we can just multiply by the number of rows.

Good luck with your alternate grid.

**Comment by firecentaur** [comment]
Hi there, in my row, I have a button, that causes a div to be display...unfortunately it is hidden because the row is not tall enougth.  Id like to be able to change the particular row via jquery - however, I am not sure how to get the css handle for the row:  - .grid1453446875998 .ui-grid-row, .grid1453446875998 .ui-grid-cell, .grid1453446875998 .ui-grid-cell .ui-grid-vertical-bar

Any ideas how I can get the .grid1453446875998 handle?

If I had it, I could change the row via jquery... plz let me know .. thanks

**Comment by jkjha** [comment]
@javid-p84 did you find alternate grid which fixes this issue and serves at-least most of the features of ui-grid. I am also stuck in same and want to know if there are any possible solution available.

**Comment by javid-p84** [comment]
@jkjha there are a bunch of grids. But we decided to change our requirements for now.
