### ISSUE TITLE
Possible to leave grid menu open after changing visibility of a single column - so can change visibility multiple columns?

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#2662]
I've got a dataset which returns ~30 columns, as mocked-up here: http://plnkr.co/edit/Kr2ppkiwxHOU0iWOxaO0?p=preview

My end users are telling me that when they are using my tool, they often have to hide/remove 5 to 10 columns; and opening the grid menu each time slows them down significantly. The old UI I had for them (using a different library) had each of the columns' name with a checkbox beside it, and they could clickity-click remove 10 columns in 2 seconds, where now each column takes 2 seconds to remove. 

Is there any way to keep a constantly-open grid menu outside of the results/table, so that it would be more repeatedly accessible?

**Comment by PaulL1** [comment]
All the grid menu is doing is toggling the visible property on the column def, then calling notifyDataChange.  So you can also build your own UI for it quite easily if you wanted to do so.

We could do a change so that when you click on a column within the grid menu it doesn't change, I think that'd be reasonably straightforward, although at the moment it closes the menu (column menu or grid menu) any time anyone clicks one of the actions, we'd need to make that switchable.  I'm not sure whether that'd be yet another option, or just change it for everyone.  

If you wanted to make that change to the source to see whether you liked that, it'd just be a case of commenting out line 240 in ui-grid-menu.js I think.  The menus would then only hide when you clicked off them, but you could see whether it gave your users what you wanted.

**Comment by juliusakula** [comment]
I think the menu staying open should be changed for everyone. 

Say I have one action to do - I open the menu, click it, menu stays open, click somewhere else. I'm not  distraught by clicking somewhere else.

Say I have two actions to do - I open the menu, click it, menu stays open, click it, click somewhere else to close; again not distraught by clicking somewhere else.

People with 1 action to do and people with multiple actions both simply click somewhere else, and neither even notices that they "have to" click outside. Not terribly obtrusive. Too simple of a thing to set on/off through gridOptions; PR submitted with removal of line 240.
