### ISSUE TITLE
Grid refresh after data has rendered

### ISSUE THREAD

**Issue by anandvihar** [angular-ui/ng-grid#2666]
gridApi.core.refresh() is not working. And how should we refresh the grid once the data has been rendered on the grid. I dont want to use auto-refresh as its performance in IE9 is pretty bad.

**Comment by pmariduena** [comment]
I'm interested in knowing this as well. I wrapped the $resource REST call that my controller makes to fetch the data, into a "reloadGrid()" method. I call that method from my UI's "Refrest button". It has worked for me, however, I have some quirks when I use it.

**Comment by PaulL1** [comment]
I think you need to provide a plunker, and a clearer description of what you expect refresh to do that you believe it's not working.  It's more likely that it doesn't do what you think it does, rather than that it's not working.  The grid should automatically render the data whenever you change it, that works off an angular binding.  You usually only need to call refresh and/or notifyDataChange if you have changed data in-place and want things like cell classes to re-render.

**Comment by PaulL1** [comment]
Possible solution offered, no response for some time, assuming raiser has resolved their issue and closing.

**Comment by diwakar-jha3110** [comment]
For me below code worked, 
            if (this.gridApi ) {
                this.$timeout(() => {
                    this.gridApi.core.handleWindowResize();
                    this.gridApi.grid.refresh();
                }, 10);
            }
