### ISSUE TITLE
[3.0.0-rc.18] ui-grid not removing all rows when asked under certain conditions

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ng-grid#2670]
Here's a plunker that reproduces the issue:
http://plnkr.co/spDnNxpQqvDhQrhY7VzL

Grid setup:
This a grid with rowEditWaitInterval = -1. multiSelect = true.

I have added an Save, Remove and Refresh button for the grid. For this example, you can ignore the Save button, as the Remove will invoke the removal operation at issue here.

I recently added a "Refresh" button, which prevents you from having to reload the entire page to update the state of the grid (which is tied to a backend service connected to a database). 

I implemented this by simply wrapping the $http call that loads the grid in a method ($scope.refresh()), and I call that method on initial page load. But, I also can call it explicitly by pressing the "Refresh" button, since I have bound that method to that UI Button.

Under normal circumstances (initial page load), the deletes work properly, i.e., if you multi select several rows, and press delete...all rows selected are removed from the grid.

Problem:
However, after you press "Refresh" even once, and do the same delete operation, there is always a left over row, despite the fact that the loop I wrote performing the removal IS properly iterating through all rowEntities.

It only goes back to normal if I reload the ENTIRE page by pressing the browser's reload button, which I am trying to avoid.

Expected Result:
Whether or not I ever press the "Refresh" button, the delete of multiple rows should work consistently.

Perhaps I'm not coding things properly in Javascript, or I'm not following some sort of best practice, or maybe there's an API method does this for me (refreshing the grid), but I think this is at least a valid use case (saving the user from having to reload the whole web page).

**Comment by PaulL1** [comment]
It's also removing rows that you didn't select.  I think the problem is that you're determining the rowIndex that you'd like to remove, but deferring the actual removal of it.  And you're doing a bunch of them.  Think about it this way:
1. I ask your code to remove rows 2, 3 and 4 from the grid, the grid has 100 rows [0, 1, 2, 3, 4, 5, ...]
2. You get the index of each of those rows, and ask it to remove rows 2, 3, 4, with each of those removals being deferred
3. The first promise runs, and we remove item in position 2 from the grid.  The grid now has [0, 1, 3, 4, 5, 6, ...]
4. The next promise runs, and we remove item in position 3 from the grid.  The item in position 3 is '4', so our grid now has [0, 1, 3, 5, 6, 7 ....]

And so on.

You need to be careful with using indexes on an array that is changing, which isn't a grid thing, it's just a general coding thing.  I'd push the indexOf into the promise itself, so that you go and find the correct item again.  Otherwise it pretty much won't work.

http://plnkr.co/edit/liRYMcAnh2RjddRWPlGB?p=preview

**Comment by pmariduena** [comment]
Hello @PaulL1 

Thanks for the JavaScript tip...it worked for me. Closing the defect.
