### ISSUE TITLE
Not correctly filtering floating point numbers

### ISSUE THREAD

**Issue by GoldyMark** [angular-ui/ng-grid#2683]
When I put ">=0" into filter input, the grid only show the cellValue which greater than 0,but not include 0.

I'm add a log to watch cellVal,the console printed 0,but the grid not.

Plunkr here:http://plnkr.co/edit/MsrhLQ
--

**Comment by PaulL1** [comment]
I think it is working as expected for whole numbers, refer: http://plnkr.co/edit/XXBcCGbZXoCSvXQA0hfK?p=preview

If you enter 2 in the filter box, it correctly filters greater than or equal to 2.  

I couldn't quite follow what your code was doing, but it looked like you were writing a custom filter condition, in which case if it is showing the wrong results it would probably be because of your custom function.

Having said that, it does appear to not be filtering by floating point numbers correctly, which I thought I'd fixed recently.  I'll take a look at that.

**Comment by GoldyMark** [comment]
I'm glad for your quickly reply.

I want to let users custom define condition rule, not only **GREATER_THAN(_OR_EQUAL)**, **LESS_THEN(_OR_EQUAL)** and other.

For example
--
When user input ***<=0.3***, then the condition function will excute ***eval(cellVal<=0.3)***;
When user input ***>=0.3***, then the condition function will excute ***eval(cellVa>=0.3)***;
When user input ***==0.3***, then the condition function will excute ***eval(cellVal==0.3)***,
and so on.

**Comment by PaulL1** [comment]
OK, do the changes I made to the filtering of floats fix the issue for you, or do you still have a problem?  If you still have a problem, it's probably something you need to work through in your condition function itself.
