### ISSUE TITLE
Blank space shows when adding new rows

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2690]
Referencing https://github.com/angular-ui/ng-grid/issues/2535#issuecomment-72177312
The issue doesn't seem limited to the infinite scroll, but happens when adding data.

I'm not quite sure what is causing it; but I can reproduce it by
1. Go to http://ui-grid.info/docs/#/tutorial/112_swapping_data demo
2. Adding a few lines then scrolling down
3. Continue to add lines, after 20+ lines added, you'll see a gap appear and will increase as you add more lines.
4. If you scroll up, the gap vanishes.

![gap](https://cloud.githubusercontent.com/assets/226331/6002574/d35c6f4e-aaf4-11e4-8596-305ab188a0a5.png)

**Comment by c0bra** [comment]
This happens due to the threshold check in GridRenderContainer's adjustRows.

It looks to see if the new scrollTop value is greater than the previous one and the new row index is greater than the previous one plus the "scroll Threshold".  This condition doesn't match because the new row index is much much less than the previous one because the scroll percentage is much less. i.e. the same scrollTop position on a canvas of 40 rows is very different than on a canvas of 30 rows.

The change that needs to be made is most likely taking the difference in scroll percentages into account and matching the row index different against that.

**Comment by c0bra** [comment]
Fixed with 509e0071b192
