### ISSUE TITLE
Date time issue

### ISSUE THREAD

**Issue by sanjayjaras** [angular-ui/ng-grid#2694]
Hi Team,
When I use cell type as date for editable grid cell, it formats properly with format provided in cell Filter. However after getting focus for edit, the format get change to mm/dd/yyyy. My column defination is as follows. Also there us no way I can add time part.
name : property.displayName,
field : property.name,
type:'date',
cellFilter: 'date:"yyyy-MM-dd HH:mm"'. Please help me with this. If possible please provide example for the same.
![screenshot from 2015-02-03 00 10 32](https://cloud.githubusercontent.com/assets/10779622/6006669/35da4e94-ab3a-11e4-8e6b-229674319968.png)
![screenshot from 2015-02-03 00 11 00](https://cloud.githubusercontent.com/assets/10779622/6006672/3d7e8958-ab3a-11e4-92b5-36da7a2e5117.png)

**Comment by anoopsinghbayes** [comment]
@sanjayjaras ,as per my knowledge chrome's input type date will pick up date format from the system that you are using ,and not from the cellfilter defined in the edit Template

**Comment by jpuri** [comment]
Hi @sanjayjaras ,
There are 2 troubles with what you are doing:
1. Though you are writing type 'Date', the actual type of javascript variable is not date but string. Thus its coming as mm/dd/yyyy instead of actual value (eg 2/3/2015).
2. Grid provides only date editor and not datetime editor. If you need to be able to edit time also please go for custom editor.

**Comment by c0bra** [comment]
No response > 2 weeks. Closing.

**Comment by ckreddy08** [comment]
Is this implemented in the new version?
