### ISSUE TITLE
Column Menu Flicker on first show

### ISSUE THREAD

**Issue by romcode** [angular-ui/ng-grid#2749]
Hi,
I have noticed that when i have multiple items added to the column menu ,
when i show it first , it has a flicker:
It's position it's updated after it's displayed on the wrong position.
http://plnkr.co/edit/s36dFIFuqwsOHG1NnhVl?p=preview
![gridissue](https://cloud.githubusercontent.com/assets/8833239/6149031/7bd781ac-b20e-11e4-909a-65fc281984c9.jpg)
Thanks

**Comment by PaulL1** [comment]
This is expected behaviour.  The menu approximates it's position based on the column width, but it doesn't know how wide it's text is (and therefore how wide it is) until it renders.  It then adjusts.  It caches the value to use as it's first guess next time - so the second time it renders it's generally more accurate.
