### ISSUE TITLE
UI-grid not automatically assigning width to columns

### ISSUE THREAD

**Issue by aneeshwp** [angular-ui/ng-grid#2770]
Whenever i set the width of column to '*' (auto-width) it does not set the width of column based on the content.

**Comment by c0bra** [comment]
That's not what the asterisk does.

**Comment by aneeshwp** [comment]
Ok , the asterisk equally divides width between all rows with width of '*', but then is there a provision for making columns get their width based on the content they have? NgGrid used to have this feature (as far as i remember) which later on broke but UiGrid was supposed to fix it .

**Comment by PaulL1** [comment]
The resize feature lets you set a column to the width of the content within it.  It would be possible to extend that feature to do this automatically on initial rendering, we'd welcome a pull request with that extension.

**Comment by c0bra** [comment]
@PaulL1 I'd suggest refiling this as a new issue that clarifies that it's an enhancement. Right now it looks and reads like a bug report.

**Comment by dimitriscsd** [comment]
I would also like to note how important this piece of functionality is.

For specific purposes the whole content of each column needs to be visible from the start.

I am using ui-grid for one of my projects and as of now the only 2 major quirks that I have come across have to do with 'fit to content' functionality.

One of them is this and the other one is have the option to set the grid height to fit exactly the content without creating a vertical scrollbar.

I would like to thank you for the otherwise great job you have done and I hope this will get even better in the future!

**Comment by PaulL1** [comment]
This is a duplicate I think of #1771: closing as there's no value in having two requests open for the same enhancement (and no current contributors looking at making this enhancement).

**Comment by wlevel** [comment]
@nekhaly  The following solution can solve this problem. 
https://github.com/angular-ui/ui-grid/issues/3913
