### ISSUE TITLE
Disable column resize on the last column

### ISSUE THREAD

**Issue by talavivi03** [angular-ui/ng-grid#2779]
Hi,

I'm wondering if it's possible to disable the resize on the last column, dynamically.
I'm using the col-reorder plugin so I can not use the "enableColumnResizing" parameter.

Looking forward to your answer.

**Comment by PaulL1** [comment]
What version are you using?  It sounds like 2.x?

**Comment by talavivi03** [comment]
it's v3.0.0-rc.16..

**Comment by PaulL1** [comment]
So that's the move columns feature, not the col-reorder plugin?  :-)

I think you can disable the resizer dynamically, and you can listen to the columnMove event to know when the columns have changed position, and therefore to change which columns you want to be resizeable.

I think it's possible to do a PR that would do this automatically, but it's a low-priority feature.  The resize feature already has some smarts around this because if a column has resize disabled and then we move it around, we have to disable all the resize handles....so a lot of the framework is already in place.

**Comment by PaulL1** [comment]
Solution suggested, no further comment for 2 weeks, assuming solution has resolved the problem.
