### ISSUE TITLE
cellNav

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2785]
initiated app with   'ui.grid.selection', 'ui.grid.cellNav',

and still cant find the scrollTo..

gridApi.cellNav.scrollTo
 Uncaught TypeError: Cannot read property 'scrollTo' of undefined

was it depreciated or lost along the way?

http://plnkr.co/edit/sJgERXoVoB00sdav3UsV?p=preview

**Comment by c0bra** [comment]
1. You don't need to supply grid or scope to `scrollTo` anymore.
2. You don't need to reference `entity`, it doesn't exist in your data model and would be on the Row object, which you're not referencing.
3. I would use $timeout instead of $interval if you're only going to do one call.

Here's an updated working plunker: http://plnkr.co/edit/yukJlcdVVxte4ZV5jK6h?p=preview

Hope that helps!

**Comment by mikila85** [comment]
Awsome!!! thank you im just realizing i wasted 4 hours googling it and trying my self when i could have seen it here:
http://ui-grid.info/docs/#/tutorial/211_two_grids
thank you!, learned my lesson work more with the docs

**Comment by ckreddy08** [comment]
Is this still working? I tried it but it does not work, get the same error, even in the plunker mentioned above, it does not work. Any ideas?

**Comment by Venkat-codeworld** [comment]
Do you have below code ?
onRegisterApi : function(gridApi) {
				vm.gridApi = gridApi;
			}
