### ISSUE TITLE
row properties have changed?

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2802]
In versions of 3.0.0-rc.18, I was defining rows with "field" and "name" properties. I found in a build of rc.19 on 2/11 that code in buildColumns drops columns if they have identical name values. This actually caused later in the code where a for-loop walked through columnDefs but also referenced self.columns (which might have less entries!)  I switched back to "field" and "displayName" and am now working again.
1. What should I really be using, and 
2. It should be possible to have to column headers with the same value.

Is the code in buildColumns wrong?
the loop   self.options.columnDefs.forEach(function (colDef, index){} drops the column
and
the loop   for (i = 0; i < self.options.columnDefs.length; i++)
gets an error!

thanks,
 steve

**Comment by PaulL1** [comment]
Name needs to be unique because the code looks up columns by name in a few places, displayName does not need to be unique.

You should be using name and displayName ideally, and field if you're giving your column a name that is other than the field name (which you have to do if you have multiple columns referring to the same field)

**Comment by steverA** [comment]
What about the code I cited that has an error if self.columns.length < options.columnDefs


/steve

Stephen R. Alpert, PhD
Principal Technical Architect
GE Healthcare
Clinical Business Solutions

T +1 617 519 2216
F +1 617 519 2625
E steve.alpert@ge.com<blocked::mailto:steve.alpert@ge.com>
www.gehealthcare.com<http://www.gehealthcare.com>

         GE imagination at work

**Comment by PaulL1** [comment]
@c0bra, this does look to be a problem.  Did you do some code recently relating to columns with duplicate names, and did this come up?

**Comment by steverA** [comment]
I receive my grid definitions from a server and had been only creating fields and names. Unfortunately, they gave me two columns with the same name (different fields). It seemed logical to have two columns with the name "Date" where their relative positions based on the adjacent left column made sense.
So, I've changed for field and displayName.

**Comment by PaulL1** [comment]
OK, fundamentally we look up columns by name in a number of places.  Name needs to be unique or that won't work.  I wonder about giving columnDefs a hashkey, and then using that hashkey instead of name, but that would be a much bigger change.

My inclination is to instead check for object equality of the associated columnDef, rather than looking for matching name.  We could probably use that everywhere instead of just checking name, which would have some benefits.  Seeking advice on that via gitter.

**Comment by steverA** [comment]
I think a simpler solution is to (a) FAQ that names have to be unique and (b) fix the code so it iterates through the smaller set to guard against the case where duplicates have been removed.

**Comment by PaulL1** [comment]
@steverA: that would prevent the error, but it would give users an unexpected result.  But I still keep seeing places in the code where name is assumed to be unique, so I'm not keen to bite off trying to use column instead.

I've created an FAQ, and changed the relevant code to:
```
      // Go through all the column defs, use the shorter of columns length and colDefs.length because if a user has given two columns the same name then 
      // columns will be shorter than columnDefs.  In this situation we'll avoid an error, but the user will still get an unexpected result
      var len = Math.min(self.options.columnDefs.length, self.columns.length);
      for (i = 0; i < len; i++) {
```

**Comment by kingcheez** [comment]
@PaulL1 Should that code be `var len = Math.min(self.options.columnDefs.length,self.columns.length+headerOffset)` or some variation? The problem is that this calculation does not take the loop into account which indexes into `self.columns` using `i+headerOffset` as an index. With the right values, that will cause an index out of bounds error.
