### ISSUE TITLE
Cell selection in conflict with scrolling

### ISSUE THREAD

**Issue by giuseppe-santoro** [angular-ui/ng-grid#2814]
You can try the bug here http://plnkr.co/edit/0YUKlkzP8qlsJCB7gjVN?p=preview.

Steps:
- click on a cell and it became selected & in editMode (**correct**)
- scroll with scrollbar and it lost the editMode but still have the focus (**correct**)
- scroll again until the selected cell is out of the grid port view and the grid set another cell as selected (**incorrect**)

The choice of the new selected cell appears to be random.

**Comment by PaulL1** [comment]
This was a tradeoff in behaviour.  We had logic that deselected the currently selected cell upon scroll, but it caused a bunch of bad side effects where we lost the focus if the scroll was triggered by the browser rather than by the user.  So we ended up with this behaviour as a compromise.  I'll mark as a bug, but note that we haven't found a way around it yet.

**Comment by PaulL1** [comment]
CellNav has been rewritten substantially.  I believe it no longer has this behaviour.  Closing.
