### ISSUE TITLE
headerRowHeight no longer working

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2822]
In the recent builds, headerRowHeight is no longer working
plunker : http://plnkr.co/edit/MhqMYOaf76o7G2Zo7hFW?p=preview

**Comment by c0bra** [comment]
Must be due to my latest alteration for dynamic header heights.

**Comment by c0bra** [comment]
I can't see that this worked in any of the RCs, even going back to rc.12.  The calculation needs to be fixed so that it can calculate the height of whatever ends up in the ui-grid-header directive. We may need to remove `replace: true` so we have a reference point.

Once that's done you can just set the height with CSS.
