### ISSUE TITLE
UI Grid Menu is shifted out when grid has horizontal scrolling

### ISSUE THREAD

**Issue by dimetrym** [angular-ui/ng-grid#2852]
* ui-grid - v3.0.0-rc.20 - 2015-02-24

Scroll grid horizontally to the last column and try to open grid menu for the last column.
Menu appears but it is displayed under another column.

![image](https://cloud.githubusercontent.com/assets/7129551/6391564/a8cd0162-bdc8-11e4-8fb6-f3d048714ef9.png)

view demo:
http://plnkr.co/edit/ArH7nYJoZd2f1wXbvoSC?p=preview

Thank you!

**Comment by PaulL1** [comment]
OK, looks like it's also doing that on the all features tutorial.  Not sure what's changed to break it, I'll take a look.

**Comment by PaulL1** [comment]
@swalters: would appreciate some advice here.  If I go to the all features tutorial, and put a breakpoint in `getColumnElementPosition`, then I click on the rightmost column menu.  It gets a positionData.left of 1200, which is presumably the leftmost border of the rightmost column.  But if I step through the code, then step into `repositionMenu`, it has a scrollLeft of 1480.  Everything goes wrong then, because we think the leftmost edge of the rightmost column is off screen to the left.  The scroll code isn't really my thing - is this something that jumps out at you as having an obvious solution, or do I need to debug through it properly?

**Comment by PaulL1** [comment]
I've done a bisect, the breakage is caused by 893bb13e08c3c8fac9e886b5021777d752761c2d, which changed the header to table style.

**Comment by gautamtrantor** [comment]
Hi,
seems the issue still replicates on firefox, with a fewer columns it works fine but when the number of column goes beyond 10-12 it occurs.
check the below snap:
![snap-uigrid](https://user-images.githubusercontent.com/23024671/32726346-b027271a-c89e-11e7-8175-a4ed180c8809.png)
the column menu displayed on some other column which was incorrect, using FF version-54.0, 64 bit

**Comment by appjacker** [comment]
Hi,
seems the issue still replicates on firefox, with a fewer columns it works fine but when the number of column goes beyond 10-12 it occurs.
check the below snap:
![snap-uigrid](https://user-images.githubusercontent.com/23024671/32726346-b027271a-c89e-11e7-8175-a4ed180c8809.png)
the column menu displayed on some other column which was incorrect, using FF version-54.0, 64 bit
