### ISSUE TITLE
Sum in Footer is 0?

### ISSUE THREAD

**Issue by TomZilla1** [angular-ui/ng-grid#2874]
Here's my dataset:
http://puu.sh/gg6Lc/6adf2d9db8.png

Been using this code:
http://ui-grid.info/docs/#/tutorial/105_footer

And it's saying 0. Does it only work with integers?

**Comment by Samy-A** [comment]
I had the same problem.

The reason in my case was that although the data looked numeric, JavaScript saw it as strings.
Try to log your dataset to the console, and see if it shows up as 1235.25 or "1235.25".

**Comment by TomZilla1** [comment]
Is there any quick fixes to this problem?

**Comment by PaulL1** [comment]
I was going to look at the aggregation logic, I'd put a breakpoint at the line that does the summing.  I'd guess that it's not automatically converting to a number, so probably it needs an explicit check as to whether it contains a number, and if so conversion to a float and then the addition.  Something similar needed doing in the filtering logic so that it did > and < with floats.

**Comment by PaulL1** [comment]
OK, I've had time to look at it.  The aggregation logic only aggregated values that were actually numbers, as opposed to numbers that could be converted to numbers. I've changed to the latter, so strings that we can convert to numbers will also aggregate.  The downside is there appear to be rounding/precision errors sometimes, refer this plunker: http://plnkr.co/edit/TPmT7tYlXTKrzl0CKj90?p=preview

Nonetheless, I think it's more useful like this, and people could add a filter to round if they needed to.
