### ISSUE TITLE
CSS issue with row heights

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#2877]
Having a css issue when rowHeight is set to 'auto'. As can be seen in this http://plnkr.co/edit/tpl:rfqcl9AHEoJZEEJxyNn2
It looks like the rows are rendering correctly, but the background color is not. I've tried looking through the css but couldn't quite figure out how the height is being applied. 
The issue seems to happen with all browsers

**Comment by c0bra** [comment]
1. 'auto' is not a valid option for rowHeight. Where did you read about that?
2. That plunker is a bare angular app.

**Comment by masterkidan** [comment]
Apologies for that, looks like I didnt save the plunk before sending it.
http://plnkr.co/edit/aKYzJzF598cCMSdOaKYm?p=preview .

Did not know it was not a valid option, decided to try it out just to see how it might work :) . Looks like it works pretty well, other than the background color.

**Comment by c0bra** [comment]
Ah, OK. Well this ends up setting all row heights to "`autopx`" which is an invalid value, so it defaults back to `auto`. This means that virtualization will break and you won't be able to stroll vertically properly. There really isn't any way to efficiently virtualize the rendering of the grid AND allow dynamic row heights, because you would have to measure the rendered height of each row as it is drawn, which with hundreds of rows would cause the browser to thrash.

There has been talk of allowing custom row heights as long as they are set explicitly, but dynamic is not something that the grid is meant to handle.

**Comment by masterkidan** [comment]
I see. That could also solve this particular issue, a row height can be computed by the client and set for each row so that the virtualization features don't get affected. Is there any plan to bring this feature out in the coming releases?

**Comment by c0bra** [comment]
Yes it's planned, just a matter of priority and having time to write it.

**Comment by masterkidan** [comment]
Thanks for the help!
