### ISSUE TITLE
Visibility always being set when restoring

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2896]
When restoring a grid, the condition that checks if a col's visibility needs to be changed is:
```javascript
grid.columns[currentIndex].visible !== columnState.visible ||
                   grid.columns[currentIndex].colDef.visible !== columnState.visible 
```
However 
```javascript columnState.visible``` and ```javascript grid.columns[currentIndex].colDef.visible``` are undefined by default so the visibility is always restored and the event is always fired.

**Comment by PaulL1** [comment]
When I work through the tutorial http://ui-grid.info/docs/#/tutorial/208_save_state with a breakpoint on that line I don't find any instances when any of column.visible, columnState.visible or column.colDef.visible are undefined.  I think the logic of the grid should prevent this from happening - the colDef is defaulted if the visible property isn't present, and then is copied down to the column.  So they should always be one or the other.

Do you have a specific example or recreation steps that I can look at so that I can resolve?

**Comment by PaulL1** [comment]
@cookednoodles: any chance of that plunker or example?

**Comment by PaulL1** [comment]
Closing, as no further information for a month, assuming this is resolved.
