### ISSUE TITLE
cellFilter not provided after saveState.save()

### ISSUE THREAD

**Issue by ackdev** [angular-ui/ng-grid#2900]
//in v3.0.0-rc.20  date CellFilter exists
$scope.state = $scope.gridApi.saveState.save();

$scope.state.columns; <-- Cell filter doesn't exist

Would like state.columns to return all column header properties such as CellFilter 

Thanks!

**Comment by PaulL1** [comment]
At the moment the saveState only saves items that the user can change, but not things that are changed programmatically, the logic being that things that are changed programmatically can be easily saved by the application without needing to interact with the grid.

It could be added though, as the saveState feature is reasonably extensible.  I'd be happy to take a look at a PR that was submitted - key things are to make it switchable (so that people who don't want that extra info don't get it), and to build unit tests.

**Comment by ackdev** [comment]
Hi, appreciate the feedback - Yes that makes sense

As a work around I'm saving state from server as that's where the default cellfilter is populated, but down the road, I was going to let the client edit cellFilter and possibly other properties as well.

My end goal is to save and restore view states, so I think this path will lead to merging of 2 view states:
1) Grid provided customization (width, filters, visibility, sorts, ordering)
2) Programatic state configuration

Then I take 1 & 2, merge together, persist.  Not impossible(doing on server now as mentioned), just seems a bit different usage wise.  The general "feel" from other components I get is the underlying object is automatically updated with state changes without having to call a savestate type method.  Not trying to redesign, just sharing my happy path.  

Thanks again!

**Comment by PaulL1** [comment]
I think it would be possible and relatively easy to extend to save more things from the columnDefs.  I didn't do so because in my application I generate those when the page first renders - so my application (similar to yours it sounds) is building a default view.  So I was already persisting that anyway, it didn't make any sense for the grid to change it.  But so long as it's switchable, I have no objection to extensions to saveState to persist more stuff.

**Comment by PaulL1** [comment]
Filters are currently saveable, and some work has been done to avoid issues with custom functions in those filters.  Closing.
