### ISSUE TITLE
need ui grid grouping example in tutotial page

### ISSUE THREAD

**Issue by smart987** [angular-ui/ng-grid#2906]
For UI grid at http://ui-grid.info/, under Advanced features,  grouping is also mentioned but when I go to http://ui-grid.info/docs/#/tutorial, I don't see any example that is related to grouping. When I was using ng grid, there used to be nice header stating 'Drag Column header here' and it would nicely group the table based on that particular column header. Can I expect that functionality in ui grid? If yes, any reference to the working example of ui grid with grouping would be helpful.

**Comment by c0bra** [comment]
Gouping isn't written yet, and should probably be removed from the page :)  It is planned, though!

**Comment by smart987** [comment]
Hi c0bra, I am little bit unclear about your comments, "and should probably be removed from the page", does it mean that you are not going to support grouping  feature in UI grid, even in future? If you are going to provide grouping feature in UI grid, is there any tentative estimation, by when we can have it? In ng grid the best part I like is the grouping feature and eagerly  looking to have it in ui grid too.

**Comment by PaulL1** [comment]
It means that we (meaning I) prematurely put it on ui-grid.info when I updated it, because I thought it would be coming soon.  That was probably 8 months ago.  But I'm building a beta version of it right as we speak, so that probably means it's not far away (purposefully vague, I hope to push something next week, but it's open source so next week can easily turn into sometime later than that).

**Comment by PaulL1** [comment]
I've pushed today, PR #2935.  This is alpha only, so the API is be no means stable, refer the new tutorial for known limitations.
