### ISSUE TITLE
Surpress/Remove error message "$apply already in progress"

### ISSUE THREAD

**Issue by totszwai** [angular-ui/ng-grid#3024]
Not sure if I am doing this right. If i trigger data update outside directive, I need to use $scope.$apply() to force the grid to refresh. However, if the data update is triggered through directive, then it would refresh automatically but then the $scope.$apply() would cause an error message.

See: http://plnkr.co/edit/XcSoBxCF4IaM4NPANPeh?p=preview

In external.js, I added a row externally when the document is ready. Works, everything looks good.
Now go to the top and click "Add blank row". It will cause:
Error: [$rootScope:inprog] $apply already in progress

**Comment by PaulL1** [comment]
This is more an angular thing than a grid thing.  Basically if you call from outside a digest cycle, then you need an apply.  If you call from within a digest cycle then you can't start another apply.  

There are two options:
- refactor so that you are always within an apply
- it is possible to check the $$phase variable to see if an apply is already in progress.  This is a bit bodgy, but works.

**Comment by totszwai** [comment]
Would it be simpler for AngularJS to ignore the apply if it an apply has already started? 
This way the user will be able to trigger the function regardless it is being called internally or externally. 

At the place where AngularJS throws that "$apply already in progress", it could simply ignores it.

**Comment by PaulL1** [comment]
Perhaps, but you'd have to ask the angularJS developers.  I presume they have a reason that they didn't think that was a good idea.

**Comment by totszwai** [comment]
Hum... right, my bad, shouldn't raised this under ng-grid. Thank you for your fast reply and insight Paul! Regards.
