### ISSUE TITLE
Grouping hide row entries for column that is grouped

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#3052]
Just started using the grouping feature. It looks pretty neat! Is it possible to hide the rows for the column that is grouped. 
Like in the example given here: http://ui-grid.info/docs/#/tutorial/209_grouping
It would be nice if the state Wyoming was not repeated for each row when it is a column used for grouping. Doing so makes it visually more terse.

**Comment by PaulL1** [comment]
I've looked at this before under another issue.  I'm working within some constraints on the UI, and one of the key constraints is to not change the underlying rows at all - I've just inserted groupHeaderRows around them.  There are two annoyances that gives me:

1. I'd like to push the group text to the left, rather than making each one stay in it's own column.  It'd be visually much more appealing.  But I'd need to use a different rowTemplate for groupHeaderRows than other rows to do that, and I haven't thought up a good way to retain the aggregations if I did that
2. I'd like to suppress some values when the column is grouped.  I could do that by replacing the cellTemplate for the column so that it only shows values in the groupHeaderRows. 

Both of those would imply a performance penalty - the scrolling gets slower when we're swapping templates in and out.  I'm not sure how much slower, so I should try it out one day to find out, at least for item 2.

**Comment by masterkidan** [comment]
Ah, didn't know about row.groupHeader. I was anyways using a cellTemplate as the cell had a hyperlink element.So, performance wise I am not noticing any significant impact.
Thanks for the tip!

**Comment by masterkidan** [comment]
I think I have found a bug with the way cellTemplates are applied when grouping is applied. This plunkr should be self explanatory:(expand the state column)
http://plnkr.co/edit/eFq8G5yfBuOvpVEgyW2P?p=preview

**Comment by PaulL1** [comment]
Looks like you found a bug where the column that we're grouping has nulls and/or undefined in it.  

Updated the plunker to massage all the data, not just the first 10 rows.

I think the cellTemplate is working fine, the problem is that both levels are group headers, if you want to apply something only at a specific level you need to check the groupLevel as well.  Look at this updated plunker: http://plnkr.co/edit/uJuEZUGi9F6o4HpUVW9z?p=preview

**Comment by PaulL1** [comment]
I've added this to the grouping tutorial (will push later today).  The cellTemplate update that you perform should be:

`cellTemplate: '<div ng-if="(!col.grouping || typeof(col.grouping.groupPriority) === \'undefined\') || ( row.groupHeader && col.grouping.groupPriority === row.groupLevel )" class="ui-grid-cell-contents" title="TOOLTIP">{{COL_FIELD CUSTOM_FILTERS}}</div>'`

**Comment by gpkarma** [comment]
Is there a way to modify that cellTemplate for the grouped row to make the column only visible when it is in the groupHeader row, and not visible when it is not a groupHeader row -- so that there is not empty space showing for the column when it is not a groupHeader row? -- and without losing the aggregates in the groupHeader row? I thought that when I applied the directions from the tutorial, including the cellTemplate mentioned above, that the data would appear the same way it does in the Grouping tutorial, however all it does is create empty space where the repeated data for the grouped column would have been.  Wondering if there is something I'm not understanding about the nature of the data used in the tutorial.

Our data comes from the backend ungrouped, though it is in order -- and when I try to make the column not visible (using "visible: false"), then the title for the groupHeader disappears as well, unfortunately.  Any help would be much appreciated.

**Comment by ketan1065** [comment]
Hi @PaulL1 
I was wondering if ng-grid has been updated with the first of the two points mentioned in your answer to this issue. I've been working on a data listing screen and would like to group my data as done in Outlook. Would help me a lot if this has been implemented. And if not, how can I accomplish that?

**Comment by PaulL1** [comment]
@ketan1065: I haven't done any work on the project for probably 2 years now.  I think that both of those things can be achieved through work in the column template, but I think you'll get quite a bit of grief with things like column resizing.  It depends how much you really want that outcome I guess.
