### ISSUE TITLE
The editDropdownOptionsArray cannot be a dynamic object

### ISSUE THREAD

**Issue by goodies4uall** [angular-ui/ng-grid#3077]
Basically we have a grid with a dropdown (column A in image) that will change values based on another dropdown's selection(column B in image). 
![capture](https://cloud.githubusercontent.com/assets/842778/6761735/815aad26-cf2c-11e4-99fd-72e2a23e9028.PNG)
However we noticed that the editDropdownOptionsArray property does a shallow copy when set to an object. If that object is later changed the grid still has the initial values.

**Comment by PaulL1** [comment]
I can't see anywhere in the code where there's a copy on the editDropdownOptionsArray, and I'm pretty sure that in my application I'm updating it.

But if you're doing this at a row level, the standard way to do that is to use the editDropdownOptionsPath, because that allows each row in the data to have a different set of dropdown options.  So if the first row has one value in column A, and the second row has a different value in column A, it will correctly give both rows different dropdowns in column B.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
