### ISSUE TITLE
ui-grid-move-columns issue -Not able to move columns properly 

### ISSUE THREAD

**Issue by njosh** [angular-ui/ng-grid#3084]
This issue is also replicable on tutorial pages

http://ui-grid.info/docs/#/tutorial/310_column_moving

when i move columns multiple times the border start getting darker and after sometime not able to move any column.Please advice

Thanks
![image](https://cloud.githubusercontent.com/assets/11484810/6768552/302020da-d099-11e4-9630-7759ac8675f4.png)

**Comment by c0bra** [comment]
Wow, that is ridiculous. Definitely a bug; thanks for reporting.

**Comment by jpuri** [comment]
This looks like something new, I will check.

**Comment by jpuri** [comment]
The problem was this "$on" in line 148 in ui-grid-header-cell.js.

                $scope.$on('$destroy', function () {
                  $contentsElm.off('mousedown touchstart');
                });

Because of this old click handlers of header cell were not removed and were creating trouble for move column when header was clicked.

**Comment by jpuri** [comment]
The reason is apparently this line of code, this is leading to event handlers being bind multiple number of times:

            var dataChangeDereg = $scope.grid.registerDataChangeCallback( updateHeaderOptions, [uiGridConstants.dataChange.COLUMN]);

@PaulL1 , this line was added as part of commit "Enh(filtering): Fix #2067 allow enabling filtering dynamically". We need to move all event bindings outside "updateHeaderOptions", so that events are not bind repeatedly. Please suggest.

**Comment by PaulL1** [comment]
@jpuri: most likely what's happening is that the dataChangeCallback is being called (via notifyDataChange), and it's registering the handlers again without removing the old ones.  The logical thing to do would be to modify the updateHeaderOptions function to remove any existing handlers before registering new ones.

**Comment by jpuri** [comment]
Hi @PaulL1 ,

What is happening is when column is moved first time one event is generated, when second time and third time 4 and number of events keep doubling. Thus move column is broken.

The reason could be when we move column, Grid is also re-rendered so some of the event handlers are just left there. If I comment the line above, its fixed.

We can do either of these:
1. Bind event only once and move code of event binding outside this function 'updateHeaderOptions'.
2. Each time function is called bind event only if it was not bind before.

As you mentioned is not possible to remove existing binding.

**Comment by PaulL1** [comment]
It should be possible to remove the existing binding - you call $off and pass in the same function that we used in $on.  That means that the function needs to be declared on the $scope so that we can always get the same instance.

Alternatively, as you say we could look at why we were adding and removing the handlers in the first place, and change it.  So instead of removing the handler, we could put an if condition in the handler and exit.  I chose not to because I figured the fewer handlers the fewer things to evaluate (and because it initially was built that way so I kept it), but you're right that we could just change that.

**Comment by jpuri** [comment]
Hi @PaulL1 ,

I agree with you and we can probably move the event attaching part outside the function. Let me start with code changes for it, once I am done I will send it over for review to you.

**Comment by PaulL1** [comment]
@jpuri: I'm probably going to look at the touch events today, which will mean I'm in this code (probably rewriting it).  I can clean up the event handlers whilst I'm at it.

**Comment by PaulL1** [comment]
I think I have resolved this as part of #3142, which also addresses touch events and correctly deregistering the event handlers.  Could you review/test?

**Comment by jpuri** [comment]
Hey @PaulL1 ,

I will test this for column.

Regards,
Jyoti

**Comment by jpuri** [comment]
Hey @PaulL1 ,

The changes look good.

**Comment by PaulL1** [comment]
Excellent, I'll just wait for someone with a windows laptop that has both touch and mouse to verify the changes, and I can merge and close all the issues.
