### ISSUE TITLE
ui-grid-resize-columns issue -view is not updated on subgrid resize

### ISSUE THREAD

**Issue by njosh** [angular-ui/ng-grid#3112]
I am facing this issue when i try to resize subgrid column on parent column resize. I have written a function which changes column width of sub grid columns on parent column resize. Its working fine if i just expand a single parent row but when i expand multiple rows and then try resizing then view of all subgrids is not updated as per parent.I need to collapse that subgrid and expand it again to reflect the changes.Currently I am using this function of api to notify subgrid of the changes :

 $scope.subGridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);

I have also tried

ui.grid.core.refresh(), refreshCanvas()

Please suggest

I have made a plunker to replicate this  : http://plnkr.co/edit/5Xtmg2V2zkzdomNh0n5P?p=preview

Thanks

![image](https://cloud.githubusercontent.com/assets/11484810/6832095/39ecf5da-d34a-11e4-8b6c-939098ee97b4.png)

**Comment by PaulL1** [comment]
It looks like what you are doing would now be done much better by grouping - because you don't really have a sub grid (with a different layout etc), you have a grouping of the same row layout.

Grouping is somewhat more performant than expandable, and also better supported.  It also doesn't need the rows to be manually aligned because they're the same rows.

**Comment by njosh** [comment]
I have almost same row layout in subgrid as parent but I have master accounts and each master account can have multiple child accounts also each master account will have its own details in the columns so i don't think i can use grouping in this case can I ? 

right now for me I think issue is with 

$scope.subGridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN) 

as it doesnt update the view of all the subgrids if they are open it only updates view of one of the subgrid.So even if i hide a subgrid column the view is not updated in other expanded subgrids till i collapse and re expand them

**Comment by PaulL1** [comment]
I can't help you much with expandable, I don't understand it well.

With grouping, it really doesn't matter where you get the data from/how you get it, only how you display it.

But yes, the group rows are generally a summary, and I think you're saying the group rows would be data rows in their own right, so that's not entirely in pattern with grouping.

**Comment by njosh** [comment]
yes exactly i will be having data in grouped rows as well.Do you have any pointer for this?

**Comment by PaulL1** [comment]
The new treeview feature should address this: http://ui-grid.info/docs/#/tutorial/215_treeView

**Comment by niranjanpawar7** [comment]
@njosh  : I m facing same issue for sub-grid alignmnet , do u have any solution for this ?
