### ISSUE TITLE
ui-grid vertical scroll with ng-switch produces unwanted behavior

### ISSUE THREAD

**Issue by sv311** [angular-ui/ng-grid#3124]
It's hard to explain so I have created a plunker to demonstrate the issue i was having.  Please see the following plunker: http://plnkr.co/edit/nCfySCStHbZbQl9TJ6lM?p=preview

The third column has a link associated with some of the rows thru ng-switch.  Notice that you see "John Doe 11" thru "John Doe 14" do not have a link associated with them.  If you hold down the scrollbar and drag it down slowly.  Eventually, you will see that the rows now have the links in the third column.

Test Environment:
Browser: Firefox 36.0.4 and Chrome Version 41.0.2272.101 m
ui-grid: latest unstable version
angular: 1.2.26U

I'm not sure what the title should be but if someone can update the title to match exactly what the problem is, that would be great.

**Comment by PaulL1** [comment]
I think you're not supposed to put {{ }} around the variable in an ng-switch: http://plnkr.co/edit/sckRTN4fno1SToDoB8m6?p=preview

When you bind like that it will resolve the value once and apply it to that cell forever - it won't change if the cell/entity value changes.  With row virtualisation we reuse the DOM elements to point to different rows, so as you scroll the entity that a particular cell is pointing to changes, we need a dynamic bind for that to work with things like templates.

**Comment by sv311** [comment]
Interesting, I changed it to COL_FIELD but same thing still happens: http://plnkr.co/edit/1UQeJZdVEocYGEniz5Jb?p=preview

**Comment by PaulL1** [comment]
And still has the same fix: http://plnkr.co/edit/yVoSgkaJhQulGXEGCPzR?p=preview

You can't use the {{ }} syntax within an angular expression as it's redundant - angular knows you're doing an ng-switch and will already evaluate the contents.  You should only use it when you're trying to put text directly into the page.

Think about it this way.  When you use the {{ }} syntax in your template, what angular will do is take the template and evaluate the {{ }} at a point in time, turning the result into static text.  It will then use that value in the ng-switch.  What you want is to leave the expression or function call there, so that angular re-evaluates it each time it looks at it, so you don't want the {{ }} syntax.

**Comment by sv311** [comment]
Ah yes, I misunderstood you the first time.  After reading it more carefully, it clicks now.  This solves my problem.  

Thank you for taking the time to look into it. 

This issue can be close.

Thanks again

**Comment by PaulL1** [comment]
Excellent, have fun out there....
