### ISSUE TITLE
CSV Export: Leading '0' values not exporting properly.

### ISSUE THREAD

**Issue by dsushmasagar** [angular-ui/ng-grid#3135]
The CSV is being exported into the correct format. However, when Excel imports the file, the leading zeros are truncated. Here is the plunker http://plnkr.co/edit/DNvncNMvCRgFYw5tfHgo?p=preview

**Comment by PaulL1** [comment]
Is that a ui-grid issue or an excel issue? We could probably force quotes around all the values, but that then breaks the data types - they'll go into Excel as strings not numbers.  Although I guess that's what you want in your case, but probably not what most people want.

EDIT: actually, looking at the file, we've already put quotes around it because it was a string not a number in javascript.  Excel is ignoring those quotes.  Not sure that there is anything we can do about that.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
