### ISSUE TITLE
Bug in Grouping while using it along with pagination.

### ISSUE THREAD

**Issue by mklbnsl** [angular-ui/ng-grid#3170]
While using Grouping with pagination, it does group only the rows present on a present page.
What should I do to group all the rows and then apply pagination.

**Comment by PaulL1** [comment]
That's not currently supported - grouping works on the visible rows, and pagination is making a set of rows invisible.

**Comment by PaulL1** [comment]
Actually, with a change I merged today, this might be fixed, as I set pagination to run after grouping.  Do you want to try again?

**Comment by PaulL1** [comment]
Assuming this is fixed - fix was merged and no response for nearly 3 weeks.

**Comment by kaycubria** [comment]
Hi @PaulL1, this seems to still be an issue for me. Do you recall how you April change was to fix this and if so, could you let me know how to enable the fix. Thanks!

**Comment by FLinares** [comment]
Same problem, any solution ?? @PaulL1

**Comment by Mohana-Lakshmi** [comment]
I have grid with grouping columns and it shows the group header row. When i added pagination , it is counting number of visible rows along with group header row.
Suppose my data is having is 4 items in one page. Pagination is displaying 5 items in one page because it is including group header row as well. please let us know the solution for this.

**Comment by Mohana-Lakshmi** [comment]
I have grid with grouping columns and it shows the group header row. When i added pagination , it is counting number of visible rows along with group header row.
Suppose my data is having is 4 items in one page. Pagination is displaying 5 items in one page because it is including group header row as well. please let us know the solution for this. @PaulL1  any help on this ???
