### ISSUE TITLE
Fix pagination tests

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#3173]
The file `pagination.spec.js` had a comma in the name. It used to be: `pagination.spec,js`, which meant karma was not picking it up for inclusion.

I have fixed the extension but the tests are broken, so I have disabled them.

@derrabus This is probably something you need to look at, correct?

**Comment by derrabus** [comment]
I'll have a look.

**Comment by derrabus** [comment]
I've finally found some time to investigate why the tests are failing. It seems that the grid is not refreshed during the test execution. The change that introduced this issue was 178ba15ada9bc49894e22a8c6b6eac589d02c119 (ping @PaulL1).

If you revert the change on pagination.js only, the tests pass. This affects some internals of the grid rendering that I'm not familiar with, so I might need a little help here.

**Comment by PaulL1** [comment]
Ah, OK.  I moved most grid.refresh() to grid.queueGridRefresh().  This means that if multiple things request a refresh during a digest cycle, we'll only do one (we seem to be accumulating lots of places that request a refresh).

In order to fix the tests, you probably need to inject $timeout into your test case, and then call $timeout.flush(), which will then trigger the grid refresh.

**Comment by derrabus** [comment]
Yes, that did the trick. Thanks. :smiley:
