### ISSUE TITLE
"TypeError: Cannot read property 'raise' of undefined" when resizing columns

### ISSUE THREAD

**Issue by davidkaminsky** [angular-ui/ng-grid#3183]
I often see this error in the console on Chrome when resizing columns. I see nothing visually indicating a problem but it does throw this error:

TypeError: Cannot read property 'raise' of undefined

And here's the stack track:

TypeError: Cannot read property 'raise' of undefined
    at ui-grid-unstable.js:19537
    at angular.js:16223
    at e (angular.js:4905)
    at angular.js:5285angular.js:11607 (anonymous function)angular.js:8557 $getangular.js:16226 (anonymous function)angular.js:4905 eangular.js:5285 (anonymous function)

**Comment by puresignal** [comment]
I was getting this too; it went away when I added the ui-grid-resize-columns directive to my grid.

**Comment by PaulL1** [comment]
The grid versions people are using are sometimes a little different.  Can you tell us what is actually at/around line 19537 of your ui-grid-unstable.js?  What directive/class is it in, what method, what line of code?

**Comment by puresignal** [comment]
If it's of any help, this was happening for me in rc.19 at line 17094, because the columnSizeChanged event had not been registered since I had only set enableColumnResizing:true as a gridOption, but failed to include the ui-grid-resize-columns directive (which I hadn't realized was necessary), which calls registerPublicApi to register the event.  Resizing was enabled and functional, but it was trying to raise a non-existent columnSizeChanged event.

        fireColumnSizeChanged: function (grid, colDef, deltaChange) {
          $timeout(function () {
            grid.api.colResizable.raise.columnSizeChanged(colDef, deltaChange);
          });
        },

**Comment by PaulL1** [comment]
I think the issue here is including the resize module but not including the resize directive.  If you do this the `uiGridResizeColumns` directive doesn't run (the directive is never called), but we still stack on top of `uiGridHeaderCell` and add the resizers.  Those resizers then error when they're used as the initialisation wasn't done.

I don't see an easy way to not stack if the directive wasn't added - that's not really how angular works.  We could do an if based on the options being set, but people could still set the options without including the directive.

I'm going to instead write an error message to the console saying "you appear to have not included the directive" which might make it clearer to people what is going on.

**Comment by davidkaminsky** [comment]
Yes, this was the problem. Thanks all!

**Comment by sugir93** [comment]
Error: a.api.colResizable is undefined

can anyone help me for the above problem ???
