### ISSUE TITLE
Issue with rendering large amount of data

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ng-grid#3191]
When I try to render large & complex set of data preferably more than or equal to (10000) rows then the browser hangs for some moment of time.  You can see the effect while switching between 
http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling
& 
http://ui-grid.info/docs/#/tutorial/190_large_dataset

I am trying with Mozilla FireFox

With Regards,
Aditya Padhi

**Comment by c0bra** [comment]
This is purely because of the large number of elements being displayed on tutorial 191. If you check the elements there's 187 different ui-grid-cells, which is therefore a lot of rendered elements on page.

This is not a typical use case where you have a gigantic number of narrow columns that are all on the page at the same time. A smaller number of columns with HUGE numbers of rows will function perfectly well.

**Comment by PaulL1** [comment]
Some changes went in over the last few weeks that addressed some anomalies that had crept in that were duplicating watchers.  The 404 tutorial in particular should demonstrate that this is working well now: http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance

**Comment by PaulL1** [comment]
Closing, no further response for over a month.
