### ISSUE TITLE
To render 150 records per page takes VERY long time

### ISSUE THREAD

**Issue by dlukianenko** [angular-ui/ng-grid#3200]
Hi, I might have a case when I need to render 150 rows per page and it takes forever to display the grid and all records. Do you have any ideas how I could speed up the render process of the grid???

Thank you

**Comment by c0bra** [comment]
That's strange; do you get similar slowness in any of the tutorials with large data sets?

And with 150 rows have you adjusted your virtualization settings? How many columns are you showing? Is your data retrieval speedy? Have you tried turning off paging to see if it loads faster?

**Comment by dlukianenko** [comment]
I'm showing 150 table rows per page. I tried to turn off paging. What do you mean adjust visualization settings ? I'm showing 12 columns. To get data from the server it takes time but to render ui-grid that takes most of all time

**Comment by PaulL1** [comment]
Could you provide a plunker?  When I modify one of the tutorials to show 150 rows (i.e. make the table height larger) it seems to perform fine: http://plnkr.co/edit/15RQg5vNeKB6yrG5YRfi?p=preview

But I may be misinterpreting what you're trying to do, since my interpretation doesn't make much sense to me.  Why would you show 150 rows, rather than using the grid scrolling?  The point of the grid is to use virtualisation to avoid rendering all the rows.  Or did I misinterpret, and you have 150 rows in a page but actually are only showing a few at a time, using scrolling as normal?

**Comment by dlukianenko** [comment]
Yes, I know and I totally agree with you about that case but it is just requirements. The customer wants to have a chance to load 250 rows on the page and scroll whole page not just grid and I'm doing my best to dance around it.

**Comment by PaulL1** [comment]
OK, so does the plunker (which does that same thing) go slow for you?  Are you able to create a plunker that does go slow so we can look at it?

**Comment by dlukianenko** [comment]
I believe I found the reason why I have this problem, my JSON structure is complex and in each sell of the grid I pass a field form the JSON which could have nested objects, arrays, array of objects and that is the reason why the ui-grid doesn't render it fast enough, to solve this problem I need to simplify my JSON which I get from the server.
Thank you for you fast reply and your plunker. It was very helpful for me to find the problem
