### ISSUE TITLE
Issue with applying cellTemplates on grouping

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#3254]
Here is a sample plunkr that describes the issue: 
http://plnkr.co/edit/LKxNuw3z0F3a7HgsLtNB?p=preview.

Essentially, I am calling a function called getText within the cellTemplate to transform the displayed text in some manner (though this is a dumb example, it may be of use if we are displaying a complex object). 

When I do so, the cellTemplate for a non-grouped column is applied at the groupingHeaderRows for some reason.

**Comment by PaulL1** [comment]
This is expected behaviour - the group rows use the same templates as the base data rows, and if you had defined, for example, aggregation on those columns, then the same template would apply.

The easiest way to deal with this in your example is to explicitly handle the undefined: http://plnkr.co/edit/w4uwJBZNjRKkjZdm1hE4?p=preview

(In your example, what you're doing would have been better handled with cellFilter than with a custom cell template, as you'd get fewer upgrade issues - refer http://ui-grid.info/docs/#/tutorial/201_editable which has a cellFilter on gender)

Alternatively, you could explicitly use an ng-if in your template and check for `!row.groupHeader`

**Comment by masterkidan** [comment]
I see. I'll go ahead with the ng-if option. But ideally this should not happen. The aggregation should only be applied when it is required and not all the time. 

I believe grouping is a feature that can be used in 2 ways. 
1. To aggregate things and apply functions such as avg, std_dev, etc.. 
2. To create a less cluttered view of the table and allowing easy navigation. 

Thanks for taking this into your future milestones.

**Comment by PaulL1** [comment]
OK, thanks for the feedback.

**Comment by windmaomao** [comment]
thanks @PaulL1 , `!row.groupHeader` works for me.
