### ISSUE TITLE
Grid empty until I export data to CSV

### ISSUE THREAD

**Issue by paambaati** [angular-ui/ng-grid#3274]
I have a grid inside a modal, and populate it with data before showing the modal. However, when the modal shows up, the grid is empty; until I export the data, after which the data shows up. The exported CSV also contains all the data. If I try to inspect the page source, I do see all my data as well.

I've tried empty `$scope.gridOptions.data` by setting its length to 0, then setting the new data, and then calling ` $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);`, but that doesn't help either.

Note that I'm using the Bootstrap modal hack included in the documentation as well, if that helps.

```
onRegisterApi: function(gridApi) {
            $scope.gridApi = gridApi;
            // Call resize every 200ms for 2s after modal finishes opening.
            // Ugly hack for making ui-grid work inside a Boostrap modal.
            $interval(function() {
                $scope.gridApi.core.handleWindowResize();
            }, 10, 500);
        }
```

**Comment by paambaati** [comment]
Never mind, I've fixed this issue by displaying the modal first, and then setting the data. Not exactly sure what the issue is, but if you're facing the exact issue, the solution is to display the grid on screen first, and then change `$scope.gridOptions.data`.

**Comment by paambaati** [comment]
Reopening because I still see this happening.

@PaulL1 Any input on this issue?

**Comment by PaulL1** [comment]
No, no good ideas.  A plunker for that one I think - it's hard to think what might be going wrong, and it's not something I've seen before.  Best guess....columnDefs not matching data?  No idea why that would fix when you exported data though.

**Comment by paambaati** [comment]
@PaulL1, @c0bra I'm trying to set up a Plunker for this; the code is quite complex and I need to abstract all employer-related stuff. For now, another 'clue' is that when I try to inspect the empty part, the data shows up. Could this be some sort of draw/redraw issue?

Also, when I say the grid is empty, it is only the canvas that doesn't show up. The pagination toolbar on the bottom also shows the correct data count (e.g. 1-3 of 3 items).

I'll try to post a screenshot when I'm able to reproduce this issue again; it is quite inconsistent for now and I'm not able to figure out a pattern yet.

**Comment by paambaati** [comment]
Quick update: The items also appear when I resize the browser window.

**Comment by PaulL1** [comment]
Hmm.  That's the exact problem that the bootstrap hack is supposed to deal with - that's why it calls `handleWindowResize`.  Are you sure that $interval is working correctly?  Have you tried maybe extending the time on the interval?  It's running 10 times, every 500ms, so it should well cover the time for the modal to load, but maybe there's something else going on in your code?

**Comment by paambaati** [comment]
@PaulL1 Alright, so when I increased the count from 10 to 1000, it seems to work. Basically, the data is getting refreshed at each interval tick.

I was under the assumption that because of the 2-way binding, if I set the data to change at any instance in time, it would just change dynamically on the grid.

**Comment by PaulL1** [comment]
If you change the data it'll change on the grid.  The issue that interval was designed to deal with was the modal popup having an incorrect size while it animates, and animation should only take a few hundred ms, so you shouldn't need to do that.  But it does tell us what's going on in a sense - you have a problem with sizing/rendering.  The fact that handleWindowResize wasn't fixing it meant I didn't know why the grid would be hiding your stuff.

The question now is what in your code happens to mess up the grid's size, that gets fixed by handleWindowResize.

I'd try doing a single repeat of the $interval, and try to work out how long it is you need before you do the handleWindowResize.  Then try to work out what's happening in your code around about then - is it waiting for the data to return from $http, or is something else happening that finishes about then.  That'll give us a lead on what's going on.

**Comment by PaulL1** [comment]
Looks resolved, closing
