### ISSUE TITLE
ui-grid auto resize performance hit

### ISSUE THREAD

**Issue by jmusser73** [angular-ui/ng-grid#3276]
I have found that if the auto resize directive is attached to an element that is "display: hidden" then the webpage takes a huge performance hit depending on the amount of grids you have on a page constantly trying to resize.

**Comment by c0bra** [comment]
So the page has some sort of visible "performance hit"  (meaning jank? lag? what?) when you use it on a hidden grid, but NOT on a normal grid?

**Comment by mbrusamolin** [comment]
I find the same issue.
I have a grid in a tab-group and when the tab is not selected the auto-resize triggers continous $scope.apply because the actual size is calculated as 0. Also gridUtil.elementHeight() and gridUtil.elementWidth() provoke a similar effect if the grid is not visible.
This cause the application on an iPad to hang within few minutes.
I found a possibile solution by preventing the call of this 3 methods. Follows my patched auto-resize.js with $elm.is(":visible") checks.

(function() {
  'use strict';
  /**
   *  @ngdoc overview
   *  @name ui.grid.autoResize
   *
   *  @description 
   *
   *  #ui.grid.autoResize
   *  This module provides auto-resizing functionality to ui-grid
   *
   */
  var module = angular.module('ui.grid.autoResize', ['ui.grid']);
  

  module.directive('uiGridAutoResize', ['$timeout', 'gridUtil', function ($timeout, gridUtil) {
    return {
      require: 'uiGrid',
      scope: false,
      link: function ($scope, $elm, $attrs, uiGridCtrl) {
        var prevGridWidth, prevGridHeight;

        function getDimensions() {
          prevGridHeight = gridUtil.elementHeight($elm);
          prevGridWidth = gridUtil.elementWidth($elm);
        }

        // Initialize the dimensions
        getDimensions();

        var resizeTimeoutId;
        function startTimeout() {
          clearTimeout(resizeTimeoutId);

          resizeTimeoutId = setTimeout(function () {
            var elemVisible = $elm.is(":visible");
            var newGridHeight = elemVisible ? gridUtil.elementHeight($elm) : 0;
            var newGridWidth = elemVisible ? gridUtil.elementWidth($elm) : 0;

            if (elemVisible && (newGridHeight !== prevGridHeight || newGridWidth !== prevGridWidth)) {
              uiGridCtrl.grid.gridHeight = newGridHeight;
              uiGridCtrl.grid.gridWidth = newGridWidth;

              $scope.$apply(function () {
                uiGridCtrl.grid.refresh()
                  .then(function () {
                    getDimensions();

                    startTimeout();
                  });
              });
            }
            else {
              startTimeout();
            }
          }, 250);
        }

        startTimeout();

        $scope.$on('$destroy', function() {
          clearTimeout(resizeTimeoutId);
        });
      }
    };
  }]);
})();

**Comment by mbrusamolin** [comment]
Seems fixed in 3.0.0.21. I removed my patch in my code.
I no loger have the problem.
Thank you

**Comment by edenchen123** [comment]
Do you think that it's better to change it to event drive? see below:

vipWidgets.directive('vpGridAutoResize', ['$timeout', 'gridUtil', function ($timeout, gridUtil) {
    return {
        require: 'uiGrid',
        scope: false,
        link: function ($scope, $elm, $attrs, uiGridCtrl) {
            var prevGridWidth, prevGridHeight, debounce;

            function getDimensions() {
                prevGridHeight = gridUtil.elementHeight($elm);
                prevGridWidth = gridUtil.elementWidth($elm);
            }

            // Initialize the dimensions
            getDimensions();
            $scope.$watch(function() { return $($elm).height(); },function(){
                $timeout.cancel(debounce);
                debounce = $timeout(function(){
                    var newGridHeight = gridUtil.elementHeight($elm);
                    var newGridWidth = gridUtil.elementWidth($elm);

                    if (newGridHeight !== prevGridHeight || newGridWidth !== prevGridWidth) {
                        uiGridCtrl.grid.gridHeight = newGridHeight;
                        uiGridCtrl.grid.gridWidth = newGridWidth;

                        $scope.$apply(function () {
                            uiGridCtrl.grid.refresh()
                                .then(function () {
                                    getDimensions();
                                });
                        });
                    }
                },200);
            });
        }
    };
}]);

**Comment by c0bra** [comment]
Glad that it's working for you!
