### ISSUE TITLE
filter.placeholder is working, but filter.term isn't

### ISSUE THREAD

**Issue by paambaati** [angular-ui/ng-grid#3284]
I have a grid that I'm displaying in a Bootstrap modal, and I'm trying to set some filter terms manually. After the modal is shown, I go about setting `$scope.gridOptions.data`, which works fine. Then, I try to set the filter term like this.

```
$scope.gridOptions.columnDefs[0].filter = {
    term: 'test',
    placeholder: 'test',
    condition: uiGridConstants.filter.EXACT
};
```

Now on the grid, I can see the placeholder showing *test*, but the term isn't set, and the data isn't filtered. What am I missing here?

**Comment by PaulL1** [comment]
We copy from the columnDefs down to the filter when the grid is originally created.  But we don't copy them later when they get changed - we don't have a way to tell they've been changed, and we don't want to copy them over top of column.filters every time we refresh anything because the user may have changed the filters themselves.

In short, if you want to change the filters programatically after rendering the grid then you should change them in `$scope.gridApi.grid.columns[0].filters[0]`.  But better would be to set them up front rather than changing them after the grid renders.

**Comment by paambaati** [comment]
Ah, got it. Changing the `filters` in `$scope.gridApi.grid.columns` seems to do the trick. Mine's a bit of a specific use-case where I don't want to set them up beforehand, because the data columns are dynamic. Do you feel this is a valid use-case we could consider?

**Comment by PaulL1** [comment]
Even if the data columns are dynamic you have the option to get the data, then set the column defs including the filters, then set the data.  You don't need to set the columnDefs right up front.

**Comment by paambaati** [comment]
@PaulL1 Fair point; I'll do that, seems like a cleaner solution. Thanks for the help!
