### ISSUE TITLE
Error when calling scrollTo

### ISSUE THREAD

**Issue by brockj** [angular-ui/ng-grid#3311]
The following error is logged when calling grid.scrollTo
asked to listen on core.on.scrollEnd but scope wasn't passed in the input parameters, you probably forgot to provide it, not registering

Scrolling seems to still work, so this is a minor issue.  The problem is that scrollToIfNecessary isn't passing in a scope
        var dereg = self.api.core.on.scrollEnd(null,function() {

I 'fixed' it locally by passing in self.appScope instead of null.  No idea if this is right or not, but it makes the error go away

You can see this issue on tutorial 202 http://ui-grid.info/docs/#/tutorial/202_cellnav

**Comment by PaulL1** [comment]
I noticed this the other day.  I added the log message about a week ago when I finally got annoyed at forgetting (again) to pass in $scope when I registered on an issue, figured I'd give an error for it.  But @swalters correctly pointed out that it's OK to pass in null, so I need to check if there's a variable in that slot that's not a $scope variable, rather than just checking that that there isn't a $scope.  I'll do something with it today.
