### ISSUE TITLE
problem with refreshing cell templates containing directives

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#3354]
Experiencing an issue while integrating ui-grid with some custom driectives using cellTemplates. 

If you look at the following plunkr: 
http://plnkr.co/edit/5OlrfLDBbwDvqjpSAaWe?p=preview

Try sorting on name, the cellTemplates don't seem to get applied properly. Don't quite understand why it is happening though

**Comment by PaulL1** [comment]
What makes you think they're not getting applied properly?  They seem to work OK - of course you've duplicated the data a number of times (or more accurately, I did when I created the large data tutorial), so if you sort you get all the "Addie Fuller"s coming to the top.  But it seems to be working.

**Comment by masterkidan** [comment]
Hmm, you are right. That was a silly mistake (got too excited when I got a repro in plunkr) 
however I do believe there is a problem:
Hopefully, this plunkr highlights the issue:
http://plnkr.co/edit/Ojws34d5KPc9XVNJEI7D?p=preview
Only the first 8 entries are supposed to have <a> tags, but by scrolling through the table, you see other entries also have the template applied on them, even when they are not supposed to. Its as if the grid caches some templates and constantly re-applies the same ones based on the scroll position without re-evaluating the templates

**Comment by PaulL1** [comment]
OK, normally that's driven by bindings not being re-evaluated.  The scroll reuses DOM elements, so you have to be careful that anything that depends on row/col is evaluated on a digest.

In this case, your problem is that you're evaluating whether the index is even (actually, <8) once, upon directive instantiation, not on every digest cycle.

This fixes it: http://plnkr.co/edit/KKKkD3fDsL818zMz952o?p=preview

**Comment by masterkidan** [comment]
That makes a lot of sense!, thanks for the quick replies, and keep up the great work.
