### ISSUE TITLE
AngularJS ng-grid- To show 'No Data Available' inside grid when its has empty data

### ISSUE THREAD

**Issue by vijender1256** [angular-ui/ng-grid#3422]
Can you please provide a workaround to show a message to display something if the grid is empty, instead of showing a blank grid, it doesn't look good at all, I tried to do this:

div ui-grid="gridOptions" ui-grid-selection ui-grid-exporter class="grid">
    div class="watermark" ng-show="!gridOptions.data.length">No data available</div>
  /div>

In CSS:

.watermark {
    position: absolute;
    top : 80px;
    opacity: 0.25;
    font-size: 3em;
    width: 100%;
    text-align: center;
    z-index: 1000;
}

But the problem is my page is bit complex and has multiple ng-grid and the message is not displayed where i wanted on the grid, its just random on the page, I want to display inside the multiple ng-grids i have, Please help me :)

**Comment by PaulL1** [comment]
The data isn't really within the control of the grid - if it doesn't have data it doesn't know whether that's because you're still loading the data or because there's no data coming. 

If you want to display a message the right way I think is to attach your own message to the grid when the data is empty.  Another option would be to do an ng-if around the entire grid, and not render the grid at all if the data length is 0.  You could then use a separate ng-if to display a message in place of the grid.  This would no doubt assist your application performance if you have a lot of grids on a page.

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.

**Comment by vijender1256** [comment]
Thank you, very much will try to implemented PaulL1

**Comment by NivedhithaV** [comment]
@vijender1256, I was looking for the same thing and this worked for me - http://stackoverflow.com/questions/28125890/angularjs-ui-grid-to-show-no-data-available-when-the-response-contains-empty
.
