### ISSUE TITLE
Header/Footer width incorrect after data and columnDefs refresh

### ISSUE THREAD

**Issue by therealtomas** [angular-ui/ng-grid#3432]
Header and footer cell width is only correct on first load, 
after data and columndefs refresh width is incorrect and not in place with its column.
See plunkr: http://plnkr.co/edit/BJ9SQBV5tgtnRzl0hcMU?p=preview

**Comment by vanxrice** [comment]
I am avoiding this issue right now by using 3.0.0-rc.20.

**Comment by dmitry-dedukhin** [comment]
+1
I've found that this happens when we use 'name' in column definition.

**Comment by nickolas1** [comment]
I'm also seeing this, but it doesn't seem related to using 'name' in columnDefs in my case.

**Comment by nickolas1** [comment]
looks like it might be 2739e02ab6bcfbfade23981890c1a3f50e5780e6
reverting the commented out block in ui-grid-header-cell.js fixes my headers. ( pinging @PaulL1 )

**Comment by dmitry-dedukhin** [comment]
In my case if I use only 'field' in columnDefs ng-grid completely rebuilds table header each time columnDefs is changed since it can't found colDef by 'name'.
If I add 'name' in columnDefs than ng-grid rebuilds only styles for table header but not header itself and than information about columns width is lost. In other words, new styles are generated for new uuids, but header columns are not rebuilded and still using class names with previous uuids.

**Comment by PaulL1** [comment]
I spent a while looking at this trying to work out what the problem was.  

I think it's behaving as expected.  When you give columnDefs that add up to 100%, the grid fills 100%.  When you give columnDefs that add up to 65%, it takes 65%.  Am I missing something, or perhaps did this used to do something different and is now fixed?

**Comment by therealtomas** [comment]
Im not sure how the grid is suppose to behave, but isnt the idea with header and footer to follow its respective column designwise? In the plunkr the "Name" column should not have a footer value, if you change data the footer value cell is not aligned with its respective value column, either its a grid error or some css error? (Im my current solution if i have col1, col2, col3, and have footer values on col2,col3, after i update data col2 footer value is in line with col1, and col3 is in line with col2)

**Comment by PaulL1** [comment]
I think you need to write a more clear description of what the defect is, because I think I'm not seeing it.

Are you saying the header and footer aren't aligned with the column?  Or are you saying the column widths are not correct?

**Comment by therealtomas** [comment]
The footer is not aligned with the column, sorry about that. Im not sure if its a bug or feature request, but on http://plnkr.co/edit/BJ9SQBV5tgtnRzl0hcMU?p=preview
![screen shot 2015-05-27 at 10 29 40](https://cloud.githubusercontent.com/assets/2316118/7831936/5de343d0-045b-11e5-8f7c-d8708fa93ca1.png)
![screen shot 2015-05-27 at 10 29 59](https://cloud.githubusercontent.com/assets/2316118/7831934/5ddf0644-045b-11e5-888b-149663d4998e.png)
![screen shot 2015-05-27 at 10 29 52](https://cloud.githubusercontent.com/assets/2316118/7831935/5de25d12-045b-11e5-8b62-f35add90bcf4.png)


If you try changing data, the footer calculation cell is not aligned with its column

**Comment by PaulL1** [comment]
Fixed this with changes a couple days back - track by uid needed to be added to footer.
