### ISSUE TITLE
[Grouping] Need support for multiple instances of column

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3435]
We should be able to apply a different aggregate function to different instances of the column. It seems that the aggregation function from the last column is applied to all column using that field.

See this plunk: http://plnkr.co/edit/MahC67?p=info

**Comment by PaulL1** [comment]
The problem here is that we write the aggregation out as an attribute on the entity associated with the groupHeader row. If you have two columns using the same field/name, then one overwrites the other.

My current thought is to do some remedial work here.  The concept is:
1.  getCellValue has an `if( headerRow )` - this needs to be more generic than just grouping, so I have to think about what the right flag is that I can put in core and doesn't imply grouping logic is bleeding into core
2.  inside that, we store the attribute under the column uid instead of the field/name
3.  we change grouping as well to put the data in the right place
4.  while we're at it, we change grouping to also store uid.tag and uid.value, so we could (if we so chose) have a cellTemplate and cellFilter that gets at these values directly instead of having to manually take them apart

The main issue with this is that I think it makes it hard for people writing custom cellTemplates.  Before a cellTemplate that worked with a normal row would also (mostly) work with a custom row.  Although arguably since getCellValue still works, this would work too....but people who rely on being able to do `row.entity.field` (like me) will get breakage.

Doing this would also deal with complex bindings, since getCellValue will now ignore those for groupHeaders.

**Comment by PaulL1** [comment]
Thinking further ahead, I think I'll write a new shared module that does base tree functions.  It's going to explicitly build a tree rather than having an array that pretends to be a tree.  At the last step it'll extract that tree to the list of rows.  That will then make it possible to do recursive sorts, and make things like expanding or counting children etc easier.

Then I think I write a "suppressSort" flag that stops the normal sort from running, and include sorting in the tree processing.

All the expand and collapse functions go into treeBase, as does sort, handling whether or not we show + when there's no children, and some other stuff.

I have a plan!!

**Comment by PaulL1** [comment]
This should be included in my treeBase branch, and should be working.

**Comment by PaulL1** [comment]
I've now merged this - does it meet your needs?

**Comment by AgDude** [comment]
The rewrite looks great. Thanks.
