### ISSUE TITLE
CellTemplate containing button directive won't click

### ISSUE THREAD

**Issue by cleon26** [angular-ui/ng-grid#3479]
I hope that I'm missing something another pair of eyes can pick out.

http://plnkr.co/edit/k4IJvJOST1240GG99PKg?p=preview

The "Regular Button" column just has a button in the column template and can fire the appscope event just fine.  The "Directive Button" column is almost the same but uses a directive to create the button except it won't launch the alert when I click it.  Am I doing something incorrectly here?  Is there some sort of a scope problem?

**Comment by PaulL1** [comment]
Looking at the code, it's a bit opaque to me because I'm not used to the controllerAs syntax.  But it looks to me like you're passing the results from a function into `btn-click`, rather than passing a pointer to a function.  I think I'd have gone another way, and tried to pass the grid, the row, and the column into the directive, rather than the click handler.  Then you can put the click handler inside the directive.  This is also fraught though, because when you scroll the row that we point to can change - so you need to be careful to pass it carefully so that it will still point to the right row when we change the row.  I seem to recall perhaps doing this by passing the $scope of the gridCell, then it always works I think.

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
