### ISSUE TITLE
[ui-grid-save-state] Placeholder gets stored and restored in gridApi.saveState.save()

### ISSUE THREAD

**Issue by nitech** [angular-ui/ng-grid#3480]
I let the user save the grid state on the server using the plugin ui-grid-save-state. 

When I call gridApi.saveState.save(), the filters object also contain the placeholder text. So when I later decided to remove the placeholder text in the configuration of the grid, the text magically reappears when gridApi.saveState.restore is called.

**Comment by PaulL1** [comment]
Yes, placeholder is one of the things it is designed to save.  You have four options:
1. Set the flag so that it doesn't save filters
2. Massage the state object so that the placeholders are removed
3. Call save state again when you remove the placeholder text
4. Remove the placeholder text again after you restore state.

**Comment by nitech** [comment]
Aha. Per design. That doesn't quite make sense to me - but you must have considered benefits that I don't see right now. 

I messed around quite a bit with Kendo UI Grid before ui-grid.info solved all my requirements, so you must have thought the specifications out quite thoroughly. Thanks!

**Comment by PaulL1** [comment]
There's a huge assumption in there - that we know what we're doing!!  I wanted to save filters, as they're clearly something a user can change that we would want to restore.  I included placeholders mostly as a side effect of that - I wanted the whole filter object because we allow people to create custom directives and therefore put custom attributes in the filter object.  I hadn't considered that people might change placeholders dynamically, so hadn't really considered needing to avoid saving them.

**Comment by nitech** [comment]
That's how development is, right? Different needs create different solutions. You must do what you think is best for ui-grid as a whole. Listen to everyone but don't do as everyone says :+1:

**Comment by PaulL1** [comment]
I think I modified this a week or so again to not save placeholder, and therefore I hope to not restore placeholder.  Could you check again?
