### ISSUE TITLE
Weird grid behavior depending on gridOptions.data parameter

### ISSUE THREAD

**Issue by Havock94** [angular-ui/ng-grid#3578]
Hi,
I was having a weird problem occuring on the data array filtering (We're using complex structure if it can help).
I was binding the gridOptions.data this way:
$scope.gridOptions.data = $scope.myComplexObject.dataArray

the weird behavior happened when the dataArray has changed due to a DB search, and the grid weren't updating the displayed rows. I had to bind the gridOptions.data again to make changes effective and be displayed in the grid.

A collegue advised to bind gridOptions.data to 'myComplexObject.dataArray' and he was right.
Binding the data to the string that references the array of objects made the grid refresh automatically upon changes like filters and record addition and deletion.

Also, the API (http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions) clearly says:
"Array of data to be rendered into the grid", so I automatically passed the object and not the name of the array.

I just wanted to report this to understand if it is supposed to be like this or just a bug. Thank you!

**Comment by PaulL1** [comment]
Yeah, I generally see a number of issues arise when people pass the array itself, rather than the string of the array name.

The key problem I usually see is people changing where the array points, and being surprised when the grid doesn't update.  That's a javascript usage problem rather than a grid problem, but changing how we recommend people interact would avoid it.  The core of the problem is:

```
  $scope.A = [ 'value1', 'value2' ];
  $scope.B = $scope.A;
  $scope.A = [ 'change1', change2' ];
```

$scope.B is still `['value1', 'value2']`, it doesn't point to $scope.A, it points to the same thing that $scope.A used to point to, and changing where $scope.A points doesn't impact $scope.B.  

Conversely, if you do:

```
  $scope.A = [ 'value1', 'value2' ];
  $scope.B = $scope.A;
  $scope.A.length = 0;
  $scope.A.push( 'change1', );
  $scope.A.push( 'change2' );
```
then $scopeB is also impacted - because we manipulated the existing array, rather than changing where $scope.A pointed.

I see a lot of people making this mistake, which is really a basic pointer thing, not a grid thing.  Changing how we recommend people interact would mitigate most of it, so I'll look to do a doco update.
