### ISSUE TITLE
getVisibleRows() doesn't get rendered version of row

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#3597]
When I use this getVisibleRows() function, it returns an array of the grid rows in sorted order, which is helpful. However I have cell template filters that turn 10000 -> 10,000; 0.01 -> 1%; etc. Is there a way I can retrieve the rows in their rendered form, programmatically? I've seen grid.getCellValue and could set up that loop (if this would return the "10,000" I want -does it?), but wouldn't getVisibleRows() want to return "what is seen"? That behaviour would be especially useful where the rendered cell is an anchor link with the cell value interpolated into the href instead of the link displayed raw

**Comment by PaulL1** [comment]
The filter is applied through an angular filter in the binding.  `{{ grid.getCellValue(row, col) | CUSTOM_FILTERS }}`

As such, the code never has access to the rendered value, and there's no good way to reapply the filter - the format that filters are in for inclusion in a binding cannot easily be changed into the right format for calling in place.

**Comment by juliusakula** [comment]
That's what I thought. So I'd need to get the filter out of the celltemplate (loads of obvious issues in this step), get the value out of the cell, apply the angular filter and get the returned the value ... Indeed not easily done

**Comment by PaulL1** [comment]
Exporter does something similar, and what I did there I think was to either provide a callback on the data as we process it so that people can apply filters, or I may have created another filter setting that takes an immediate filter in the form of a function - I know I did that on some of the menus.  So you can achieve the outcome, it's just not as pretty.

I have a niggle in my mind about replacing the whole `getCellValue() | CUSTOM_FILTERS` setup with a custom binding that we calculate and render into the cell, and then only recalculate when we need to (which wouldn't include scrolling).  It would mean fewer watchers for things like columns, rows, and for the cellTooltip.  But that would very much un-angular our code.

**Comment by c0bra** [comment]
@PaulL1 does this need to turn into a different issue, or can it be merged with another issue that maybe already exists for the custom cell binding?

**Comment by PaulL1** [comment]
Yes and no.  I don't think we'll ever do it, because it would imply getting rid of the binding in the cellTemplate entirely, and that's too anti-angular.  Closing.
