### ISSUE TITLE
columnFooter has undefined/Nan/Infinity/-Infinity values when data is grouped

### ISSUE THREAD

**Issue by holly-weisser** [angular-ui/ng-grid#3625]
See Plunkr:

http://plnkr.co/edit/6djeNT1fex39E9c4vwNE

It's an edit of the one found here:

http://ui-grid.info/docs/#/tutorial/105_footer

I simply added a group on the name column.

**Comment by c0bra** [comment]
@PaulL1 grouping is your bailiwick, yes? :)

**Comment by PaulL1** [comment]
The problem is likely to be that grouping adds labels into the grouping subtotals, which means the aggregation cannot work any more.  More importantly, when you use footer aggregation with grouping it aggregates the group header rows as well as the core data, and therefore gets the wrong answer.  Footer aggregation and grouping are not compatible.

**Comment by PaulL1** [comment]
@swalters: do you have any objection if I modify aggregation (in the footers) to ignore any group header rows?  It'd still aggregate tree headers, as they are part of the data, but group headers are added by grouping, and therefore not part of the base data.

**Comment by PaulL1** [comment]
OK, looking at this again, it's actually working as designed, albeit that is not obvious to users.  When you have all the rows collapsed, there's no visible rows to aggregate, so it basically returns null/NaN etc.  Aggregation only totals visible rows, and grouping makes most of the rows invisible.  If you expand one of the groups it starts working, although the values that it gives aren't overly useful.

I'll write something into the tutorials that makes it clear that column footers and grouping don't go well together.
