### ISSUE TITLE
v3.0.0-rc.21: Removing a filter in a > or < column doesn't clear the filter

### ISSUE THREAD

**Issue by DenAnderson** [angular-ui/ng-grid#3678]
If you type into a filter in a string column, then backspace to remove the filter the 'x' delete widget disappears and the filter is cleared. All well and good.

If you type into a greater than or less than filter and do the same a value of 0 appears to be left.

This can be reproduced on the grid here http://ui-grid.info/docs/#/tutorial/103_filtering.
Enter a value into the Age 'less than' box, say 30, and the grid filters fine. Now backspace to remove this filter and you're left with 1 row where the age is -1. The same applies to the 'greater than', in this case the row with -1 is missing.

Do the same in the Name filter and it works fine.

**Comment by PaulL1** [comment]
Ah.  That turns out to be where I was lazy and forgot that I'd been.  It works correctly if there is only one filter.  If there's more than one filter at some point I assumed that at least one of them would have a term.  Which isn't a reasonable assumption, but at the time I thought it was (I think at the time I thought we'd only have multiple filters when someone had filled in one, and there'd be some logically to automagically show a second filter box).

Fixed now.
