### ISSUE TITLE
Issue with rendering rows using Infinite Scroll, row backgrounds will alternate with each other when you scroll

### ISSUE THREAD

**Issue by vhalbwachs** [angular-ui/ng-grid#3733]
The background color of the odd/even rows switch every time you scroll in the grid.

For an example, see the following plunker: (Taken from the docs)

http://plnkr.co/edit/zyE4Q2bvnmyEfQ74H5zf?p=preview

Scroll and notice that the background colors will alternate every time you scroll down (or up)

Tested on Chrome 42 + Firefox 40, running OSX Yosemite.

**Comment by vhalbwachs** [comment]
Here's a gif of the issue, if that's helpful:

![scroll](https://cloud.githubusercontent.com/assets/5904405/8049272/e9f6b23e-0e11-11e5-98c8-06ee75bb83fe.gif)

**Comment by PaulL1** [comment]
Duplicate of #3369 I believe.

**Comment by vhalbwachs** [comment]
Yes, it looks like that's the same issue. Sorry about that, I had searched through the issues to try and make sure I wasn't opening a duplicate issue, but had missed that one.

Interestingly enough, this only happens when the `infiniteScroll` feature is being used. When I'm not using infinite scroll, ui-grid works like a charm. I will try and look into why that feature causes it to behave like this.

In the meantime, do you want me to close the issue and continue it on #3369 ?

**Comment by PaulL1** [comment]
Yeah, close and merge probably makes sense.  I think it does it without infinite scroll as well - basically what it's doing is showing alternate colours for the rendered rows, not for the visible rows.  Since it's a css property, it doesn't know about anything that's not rendered.  We could push the visible row index into the code somewhere, and then try to have the css calculate odd/even on that instead, but I'm not sure the performance implications of that.

**Comment by vhalbwachs** [comment]
Closed: Duplicate of #3369
