### ISSUE TITLE
How to update class of one cell of grid

### ISSUE THREAD

**Issue by ritasakhuja** [angular-ui/ng-grid#3744]
Hi 
We have grid with different class.
Few of the cells have custom.html data.
We need to update the class of selected cell based on some actions.
Please tell me how to update the cell class/css from JS for grid

**Comment by c0bra** [comment]
When you say "selected" do you mean selected by the user, or selected by your programming?

**Comment by ritasakhuja** [comment]
when user selects the grid,i cache the information of selection like rowentitity,coldef etc.Then one confirmation dialog comes.If user says no then I want to apply some different class to grid or if he says yes then I want to apply some different class.
I need solution both way cell selected by user or programming,I need to update the grid cell class.

I tried functions like refersh,cellClass or notifychange but no help.

**Comment by ritasakhuja** [comment]
Please update me with some solution

**Comment by PaulL1** [comment]
Have you tried using the cellClass option, and perhaps setting it based on a variable in your code that you set from your modal?  Could you provide a plunker of what you've tried?

**Comment by ritasakhuja** [comment]
Hi
Thanks for the reply.
I did the same and my issue is resolved now.

Regards
Rita


Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: Brian Hann <notifications@github.com> </div><div>Date:2015/06/10  8:47 PM  (GMT+05:30) </div><div>To: angular-ui/ng-grid <ng-grid@noreply.github.com> </div><div>Cc: ritasakhuja <ritasakhuja@gmail.com> </div><div>Subject: Re: [ng-grid] How to update class of one cell of grid (#3744) </div><div>
</div>When you say "selected" do you mean selected by the user, or selected by your programming?

**Comment by rajush** [comment]
Hey guys, sorry for adding on to this one, as i saw this one pretty close to the issue i'm dealing with. 

So what i'm trying to achieve is, on after cell edit, it should do a ajax call and then do the input value validation against the returned data to change the color class of that edited cell.

Here is the plunkr http://plnkr.co/edit/bVieULC1SPjLZwY4OzWJ?p=preview

So, on file import i'm able to do the class change by using 'cellClass option' after ajax call since it's an import and the cell values are pre-defined. Now,  if the cell is edited individually, it will/should do a ajax call again and then validate the input value against the returned data to change the 'cellClass'. The later part has been breaking on me, since it's ajax call on 'cellClass' option. Not sure how exactly how to implement this functionality.

Please suggest possible way to implement this.

Thank you!
