### ISSUE TITLE
isRowSelected refresh after data is modified

### ISSUE THREAD

**Issue by TJSoftware** [angular-ui/ng-grid#3955]
I found [this defect](https://github.com/angular-ui/ng-grid/issues/3054) that seems to describe the issue I am seeing and it is marked as closed.  I am still seeing this issue with the latest version of Angular.  Please see the [plunker](http://plnkr.co/edit/UKMM2kNaTpxUzsdn6RDB?p=preview) that I created from the [selection](http://ui-grid.info/docs/#/tutorial/210_selection) example.  I change the first row age value then call `$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ROW);`.  However, I am still not allowed to select the row.

**Comment by JLLeitschuh** [comment]
Can you please list out the series of steps that you have to go through in order to experience this problem?
There are way too many buttons in your example to clearly demonstrate what series of actions causes the problem that you are seeing.
If there is any way to reduce the number of buttons/elements in that example that would also be appreciated.

**Comment by TJSoftware** [comment]
Ahh, the process of describing things, it always makes you smack yourself in the face.  First you realize that you did not tell anything about how to get the problem, then you realize how to solve the problem when you do explain the steps.  

Instead of using  `$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ROW);` I used  `$scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.EDIT);`.  I realized this after clicking the "Set Selectable" the ability to check or not check the first row changed (what I was trying to achieve with the "Set First Age to ##" buttons).  Thanks for responding.
